import { BadRequestException, ConflictException, Injectable } from '@nestjs/common';
import { Prisma, Role } from '@prisma/client';
import argon2 from 'argon2';
import { PrismaService } from '../../common/prisma.service';
import { locationFreshness } from '../../common/live-policy';
@Injectable()
export class AdminService {
 constructor(private db:PrismaService){}
 private audit(actorId:string,action:string,entityType:string,entityId:string){return this.db.auditLog.create({data:{actorId,action,entityType,entityId}});}
 dashboard(){const day=new Date();day.setHours(0,0,0,0);return Promise.all([this.db.trip.count({where:{status:'ACTIVE'}}),this.db.trip.count({where:{status:'ACTIVE',vehicle:{type:'BUS'}}}),this.db.trip.count({where:{status:'ACTIVE',vehicle:{type:'VAN'}}}),this.db.trip.count({where:{status:'COMPLETED',endedAt:{gte:day}}})]).then(([activeTrips,activeBuses,activeVans,completedToday])=>({activeTrips,activeBuses,activeVans,driversOnActiveTrips:activeTrips,completedToday}));}
 drivers(){return this.db.driver.findMany({include:{user:{select:{email:true,phone:true,accountStatus:true}},vehicles:true},orderBy:{lastName:'asc'}});}
 async createDriver(actorId:string,d:any){const created=await this.db.user.create({data:{email:d.email.toLowerCase(),phone:d.phone,passwordHash:await argon2.hash(d.password),role:Role.DRIVER,driver:{create:{firstName:d.firstName,lastName:d.lastName}}},include:{driver:true}});await this.audit(actorId,'driver.created','Driver',created.driver!.id);return{id:created.driver!.id,email:created.email,firstName:d.firstName,lastName:d.lastName};}
 async driverStatus(actorId:string,id:string,active:boolean){const driver=await this.db.driver.update({where:{id},data:{active,user:{update:{accountStatus:active?'ACTIVE':'DISABLED'}}}});await this.audit(actorId,'driver.status.changed','Driver',id);return driver;}
 vehicles(){return this.db.vehicle.findMany({include:{assignedDriver:true},orderBy:{displayName:'asc'}});}
 async createVehicle(actorId:string,d:any){if(d.assignedDriverId&&!await this.db.driver.findFirst({where:{id:d.assignedDriverId,active:true}}))throw new BadRequestException('Active driver required');const v=await this.db.vehicle.create({data:d});await this.audit(actorId,'vehicle.created','Vehicle',v.id);return v;}
 stops(){return this.db.stop.findMany({orderBy:{name:'asc'}});}
 async createStop(actorId:string,d:any){const s=await this.db.stop.create({data:d});await this.audit(actorId,'stop.created','Stop',s.id);return s;}
 routes(){return this.db.route.findMany({include:{stops:{include:{stop:true},orderBy:{sequence:'asc'}}},orderBy:{name:'asc'}});}
 async createRoute(actorId:string,d:any){if(d.stops.length<2)throw new BadRequestException('A route needs at least two stops');const seq=d.stops.map((x:any)=>x.sequence),ids=d.stops.map((x:any)=>x.stopId);if(new Set(seq).size!==seq.length||new Set(ids).size!==ids.length)throw new BadRequestException('Stop and sequence values must be unique');const active=await this.db.stop.count({where:{id:{in:ids},active:true}});if(active!==ids.length)throw new BadRequestException('All stops must exist and be active');const route=await this.db.route.create({data:{name:d.name,direction:d.direction,stops:{create:d.stops}},include:{stops:{include:{stop:true},orderBy:{sequence:'asc'}}}});await this.audit(actorId,'route.created','Route',route.id);return route;}
 async createSchedule(actorId:string,d:any){const at=new Date(d.departureAt),from=new Date(at.getTime()-4*3600_000),to=new Date(at.getTime()+4*3600_000);const [route,driver,vehicle,conflict]=await Promise.all([this.db.route.findFirst({where:{id:d.routeId,active:true}}),this.db.driver.findFirst({where:{id:d.driverId,active:true}}),this.db.vehicle.findFirst({where:{id:d.vehicleId,active:true,assignedDriverId:d.driverId}}),this.db.schedule.findFirst({where:{active:true,departureAt:{gte:from,lte:to},OR:[{driverId:d.driverId},{vehicleId:d.vehicleId}]}})]);if(!route||!driver||!vehicle)throw new BadRequestException('Active route and assigned active driver/vehicle required');if(conflict)throw new ConflictException('Driver or vehicle has an overlapping assignment');const schedule=await this.db.schedule.create({data:{...d,departureAt:at,trip:{create:{routeId:d.routeId,driverId:d.driverId,vehicleId:d.vehicleId,scheduledDepartureAt:at,status:'READY'}}},include:{trip:true}});await this.audit(actorId,'schedule.created','Schedule',schedule.id);return schedule;}
 async live(){const trips=await this.db.trip.findMany({where:{status:'ACTIVE'},include:{currentLocation:true,vehicle:true,driver:true,route:true}});return trips.map(t=>({...t,gpsStatus:t.currentLocation?locationFreshness(t.currentLocation.recordedAt):'OFFLINE'}));}
}
