import NetInfo from '@react-native-community/netinfo';
import {mobileColors as colors,radii,spacing,SUGAT_BRAND_TAGLINE,touchTarget} from '@sugat/theme';
import {StatusBar}from'expo-status-bar';
import React,{useCallback,useEffect,useMemo,useState}from'react';
import{ActivityIndicator,Alert,FlatList,KeyboardAvoidingView,Modal,Platform,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import MapView,{Marker}from'react-native-maps';
import{SafeAreaProvider,SafeAreaView}from'react-native-safe-area-context';
import{io}from'socket.io-client';
import{api,ApiError,login,logout as revokeSession,SOCKET_URL}from'./src/api';
import{accessToken,clearSession}from'./src/session';

type Screen='dashboard'|'live'|'trips'|'more'|'drivers'|'vehicles'|'routes';type Row=Record<string,any>;type Data={dashboard:Row;live:Row[];schedules:Row[];drivers:Row[];vehicles:Row[];routes:Row[]};
const ADMIN_TABS:Screen[]=['dashboard','live','trips','more'];
const driverName=(driver?:Row)=>driver?[driver.firstName,driver.middleName,driver.lastName].filter(Boolean).join(' '):'Unassigned';
let navigateAdmin:(screen:Screen)=>void=()=>{};
export default function App(){const[booting,setBooting]=useState(true),[authenticated,setAuthenticated]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[screen,setScreen]=useState<Screen>('dashboard'),[data,setData]=useState<Data|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[online,setOnline]=useState(true);
 navigateAdmin=setScreen;
 const load=useCallback(async()=>{setBusy(true);try{const[dashboard,live,schedules,drivers,vehicles,routes]=await Promise.all(['/admin/dashboard','/admin/live','/admin/schedules','/admin/drivers','/admin/vehicles','/admin/routes'].map(path=>api<any>(path)));setData({dashboard,live,schedules,drivers,vehicles,routes});setError('')}catch(caught){const message=caught instanceof Error?caught.message:'Unable to load operations.';setError(message);if(caught instanceof ApiError&&[401,403].includes(caught.status??0)){await clearSession();setAuthenticated(false)}}finally{setBusy(false)}},[]);
 useEffect(()=>{void accessToken().then(token=>{setAuthenticated(Boolean(token));if(token)return load()}).finally(()=>setBooting(false))},[load]);useEffect(()=>NetInfo.addEventListener(state=>setOnline(Boolean(state.isConnected&&state.isInternetReachable!==false))),[]);
 useEffect(()=>{if(!authenticated)return;let socket:any;const subscribe=()=>socket.emit('admin.subscribe',(ack:{ok:boolean;subscribed?:boolean;message?:string})=>{if(!ack?.ok||!ack.subscribed){setError(ack?.message??'Realtime authorization failed.');socket.disconnect()}});void accessToken().then(token=>{socket=io(`${SOCKET_URL}/live`,{auth:{token},transports:['websocket']});socket.on('connect',subscribe);socket.on('trip.started',load);socket.on('trip.location.updated',load);socket.on('trip.completed',load);socket.on('trip.occupancy.updated',load)});return()=>{if(socket){socket.off('connect',subscribe);socket.off('trip.started',load);socket.off('trip.location.updated',load);socket.off('trip.completed',load);socket.off('trip.occupancy.updated',load);socket.disconnect()}}},[authenticated,load]);
 async function signIn(){setBusy(true);setError('');try{await login(email.trim(),password);setAuthenticated(true);await load()}catch(caught){setError(caught instanceof Error?caught.message:'Login failed.')}finally{setBusy(false)}}
 function logout(){Alert.alert('Log out of SUGAT Admin?','Your secure admin session will be revoked and removed from this device.',[{text:'Cancel',style:'cancel'},{text:'LOG OUT',style:'destructive',onPress:()=>void revokeSession().finally(()=>{setAuthenticated(false);setData(null);setPassword('')})}])}
 if(booting)return<Shell><Center text="RESTORING SECURE SESSION…"/></Shell>;
 if(!authenticated)return<Shell><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined}style={styles.login}><Wordmark/><Text style={styles.loginTitle}>Operations Login</Text><Text style={styles.secondary}>Sign in to manage SUGAT operations.</Text><TextInput accessibilityLabel="Admin email"style={styles.input}autoCapitalize="none"keyboardType="email-address"placeholder="Admin email"value={email}onChangeText={setEmail}/><TextInput accessibilityLabel="Password"style={styles.input}secureTextEntry placeholder="Password"value={password}onChangeText={setPassword}/>{error?<Text accessibilityRole="alert"style={styles.error}>{error}</Text>:null}<Button label={busy?'SIGNING IN…':'SIGN IN'}disabled={busy||!email||!password}onPress={()=>void signIn()}/></KeyboardAvoidingView></Shell>;
 return<Shell><View style={styles.app}>{!online&&<Text style={styles.offline}>OFFLINE — MUTATIONS DISABLED</Text>}<View style={styles.top}><Wordmark/><Pressable onPress={logout}><Text style={styles.logout}>LOG OUT</Text></Pressable></View><ScrollView refreshControl={<RefreshControl refreshing={busy}onRefresh={()=>void load()}tintColor={colors.gold}/>}contentContainerStyle={styles.content}>{error?<Text accessibilityRole="alert"style={styles.error}>{error}</Text>:null}{!data?<Center text="LOADING OPERATIONS…"/>:screen==='more'?<AdminMore/>:<ScreenContent screen={screen}data={data}online={online}reload={load}/>}</ScrollView><View style={styles.nav}>{ADMIN_TABS.map(item=><Pressable accessibilityRole="tab" key={item}onPress={()=>setScreen(item)}style={[styles.navItem,screen===item&&styles.navActive]}><Text style={[styles.navText,screen===item&&styles.navTextActive]}>{item==='dashboard'?'HOME':item.toUpperCase()}</Text></Pressable>)}</View></View></Shell>}
function ScreenContent({screen,data,online,reload}:{screen:Screen;data:Data;online:boolean;reload:()=>Promise<void>}){if(screen==='dashboard')return<><Hero metrics={data.dashboard}/><Text style={styles.section}>OPERATIONS SUMMARY</Text><Metrics values={data.dashboard}/><Button label="VIEW LIVE OPERATIONS"onPress={()=>{}}disabled/><Text style={styles.note}>Use the LIVE tab for the current fleet map and GPS status.</Text></>;if(screen==='live')return<Live rows={data.live}/>;if(screen==='trips')return<List title="LEGACY SCHEDULES"rows={data.schedules}render={row=><><Chip text={row.trip?.status??'NO TRIP'}/><Text style={styles.cardTitle}>{row.route.name}</Text><Text style={styles.secondary}>{driverName(row.driver)} · {row.vehicle.displayName}</Text><Text style={styles.note}>{new Date(row.departureAt).toLocaleString()}</Text></>}/>;if(screen==='drivers')return<List title="DRIVERS"rows={data.drivers}render={row=><><Chip text={row.active?'ACTIVE':'INACTIVE'}/><Text style={styles.cardTitle}>{driverName(row)}</Text><Text style={styles.secondary}>{row.user.email} · {row.user.phone??'No mobile'}</Text><Text style={styles.note}>{row.vehicles.length} assigned vehicle(s)</Text><DriverAccess driver={row} routes={data.routes} online={online} reload={reload}/></>}/>;if(screen==='vehicles')return<List title="VEHICLES"rows={data.vehicles}render={row=><><Chip text={row.active?'ACTIVE':'INACTIVE'}/><Text style={styles.cardTitle}>{row.displayName}</Text><Text style={styles.secondary}>{row.type} · {row.plateNumber}</Text><Text style={styles.note}>Driver: {driverName(row.assignedDriver)}</Text></>}/>;if(screen==='routes')return<List title="ROUTES"rows={data.routes}render={row=><><Chip text={row.active?'ACTIVE':'INACTIVE'}/><Text style={styles.cardTitle}>{row.name}</Text><Text style={styles.secondary}>{row.direction}</Text><Text style={styles.note}>{row.stops.map((item:Row)=>item.stop.name).join(' → ')}</Text></>}/>;return null}

function DriverAccess({driver,routes,online,reload}:{driver:Row;routes:Row[];online:boolean;reload:()=>Promise<void>}){
 const[editing,setEditing]=useState(false),[ids,setIds]=useState<string[]>((driver.authorizedRoutes??[]).filter((grant:Row)=>grant.route.active).map((grant:Row)=>grant.route.id)),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(){setBusy(true);try{await api('/admin/drivers/'+driver.id+'/routes',{method:'PATCH',body:JSON.stringify({routeIds:ids})});setEditing(false);await reload()}catch(caught){setError(caught instanceof Error?caught.message:'Update failed.')}finally{setBusy(false)}}
 function reset(){Alert.alert('Reset authorized device?','The old phone and all driver sessions will lose access. The next successful login will authorize a device.',[{text:'Cancel',style:'cancel'},{text:'RESET',style:'destructive',onPress:()=>{setBusy(true);void api('/admin/drivers/'+driver.id+'/device/reset',{method:'POST'}).then(reload).catch(caught=>setError(caught.message)).finally(()=>setBusy(false))}}])}
 return <><Text style={styles.note}>Device: {driver.authorizedDevice?'AUTHORIZED':'NOT REGISTERED'}</Text><Button label="AUTHORIZED ROUTES" disabled={!online||busy} onPress={()=>setEditing(!editing)}/>{editing&&<><Text style={styles.note}>Authorize routes; drivers choose when to depart.</Text>{routes.filter(route=>route.active).map(route=><Pressable key={route.id} accessibilityRole="checkbox" accessibilityState={{checked:ids.includes(route.id)}} onPress={()=>setIds(current=>current.includes(route.id)?current.filter(id=>id!==route.id):[...current,route.id])} style={styles.select}><Text style={styles.secondary}>{ids.includes(route.id)?'☑':'☐'} {route.name} · {route.direction}</Text></Pressable>)}<Button label="SAVE AUTHORIZATIONS" disabled={busy||!online} onPress={()=>void save()}/></>}<Button label="RESET AUTHORIZED DEVICE" disabled={busy||!online} onPress={reset}/>{error&&<Text style={styles.error}>{error}</Text>}</>;
}

function AdminMore(){return<><Text style={styles.section}>MORE OPERATIONS</Text><Text style={styles.secondary}>Open a focused management area.</Text>{([['drivers','Drivers'],['vehicles','Vehicles'],['routes','Routes']]as [Screen,string][]).map(([target,label])=><Pressable accessibilityRole="button"key={target}onPress={()=>navigateAdmin(target)}style={styles.select}><Text style={styles.cardTitle}>{label}</Text><Text style={styles.note}>View and manage supported {label.toLowerCase()} workflows.</Text></Pressable>)}</>}
function Hero({metrics}:{metrics:Row}){return<View accessibilityLabel="SUGAT operations summary"style={[styles.hero,{minHeight:170}]}><View style={styles.heroCopy}><Text style={[styles.heroTitle,{marginTop:0}]}>OPERATIONS SUMMARY</Text><Text style={styles.heroSubtitle}>Monitor live trips, drivers, and compliance.</Text><View style={styles.heroMetrics}><Mini label="ACTIVE TRIPS"value={metrics.activeTrips}/><Mini label="GPS STALE"value={metrics.gpsStale}/></View></View></View>}
function Wordmark({reversed=false}:{reversed?:boolean}){return<View style={styles.wordmark}><Text style={[styles.brand,reversed&&{color:colors.white}]}>SUGAT</Text><Text style={[styles.brandTagline,reversed&&{color:colors.borderStrong}]}>{SUGAT_BRAND_TAGLINE}</Text></View>}
function Metrics({values}:{values:Row}){return<View style={styles.metricGrid}>{Object.entries({activeTrips:'Active Trips',activeBuses:'Active Buses',activeVans:'Active Vans',gpsStale:'GPS Stale',licensesExpiringWithin30Days:'Licenses ≤30 Days',licensesExpiringWithin7Days:'Licenses ≤7 Days',expiredLicenses:'Expired Licenses',driversPendingVerification:'Pending Verification'}).map(([key,label])=><View style={styles.metric}key={key}><Text style={styles.metricValue}>{values[key]??'—'}</Text><Text style={styles.note}>{label}</Text></View>)}</View>}
function Mini({label,value}:{label:string;value:any}){return<View><Text style={styles.miniValue}>{value??'—'}</Text><Text style={styles.miniLabel}>{label}</Text></View>}
function Live({rows}:{rows:Row[]}){const located=rows.filter(row=>row.currentLocation),center=located[0]?.currentLocation;return<><Text style={styles.section}>LIVE FLEET</Text><View style={styles.map}>{center?<MapView style={StyleSheet.absoluteFill}initialRegion={{latitude:center.latitude,longitude:center.longitude,latitudeDelta:.5,longitudeDelta:.5}}>{located.map(row=><Marker key={row.id}coordinate={row.currentLocation}title={row.vehicle.displayName}description={`${row.gpsStatus} · ${row.route.name}`}pinColor={row.complianceAlert?colors.danger:row.gpsStatus==='LIVE'?colors.success:colors.gold}/>)}</MapView>:<Center text="NO ACTIVE VEHICLE LOCATIONS"/>}</View>{rows.length?rows.map(row=><Card key={row.id}><Chip text={`GPS ${row.gpsStatus}`}/>{row.complianceAlert?<Text style={styles.error}>COMPLIANCE ALERT — {row.complianceAlert.code}: {row.complianceAlert.message}</Text>:null}<Text style={styles.cardTitle}>{row.vehicle.displayName}</Text><Text style={styles.secondary}>{row.route.name} · {driverName(row.driver)}</Text><Text style={styles.note}>Next: {row.nextStop?.name??'Final destination'} · Updated {row.currentLocation?new Date(row.currentLocation.recordedAt).toLocaleString():'Never'}</Text></Card>):<Empty text="No trips are currently active."/>}</>}
function List({title,rows,render}:{title:string;rows:Row[];render:(row:Row)=>React.ReactNode}){const[query,setQuery]=useState('');const shown=rows.filter(row=>JSON.stringify(row).toLowerCase().includes(query.toLowerCase()));return<><Text style={styles.section}>{title}</Text><TextInput style={styles.input}placeholder="Search real records"value={query}onChangeText={setQuery}/>{shown.length?shown.map(row=><Card key={row.id}>{render(row)}{title==='DRIVERS'&&row.compliance?<><Chip text={row.compliance.licenseValidity}/><Text style={styles.note}>{row.compliance.eligible?'Eligible to start a trip':`${row.compliance.code}: ${row.compliance.message}`}</Text></>:null}</Card>):<Empty text="No matching records."/>}</>}
function SelectButton({label,value,onPress}:{label:string;value:string;onPress:()=>void}){return<Pressable onPress={onPress}style={styles.select}><Text style={styles.eyebrow}>{label}</Text><Text style={styles.cardTitle}>{value||'Tap to select'}</Text></Pressable>}
function Choice({visible,title,rows,close,select}:{visible:boolean;title:string;rows:Row[];close:()=>void;select:(row:Row)=>void}){return<Modal visible={visible}animationType="slide"onRequestClose={close}><SafeAreaView style={styles.modal}><View style={styles.row}><Text style={styles.section}>{title}</Text><Pressable onPress={close}><Text style={styles.logout}>CLOSE</Text></Pressable></View><FlatList data={rows}keyExtractor={row=>row.id}renderItem={({item})=><Pressable style={styles.choice}onPress={()=>select(item)}><Text style={styles.cardTitle}>{item.displayName??item.name??driverName(item)}</Text><Text style={styles.secondary}>{item.plateNumber??item.direction??item.user?.email}</Text></Pressable>}ListEmptyComponent={<Empty text="No eligible records."/>}/></SafeAreaView></Modal>}
function Shell({children}:{children:React.ReactNode}){return<SafeAreaProvider><SafeAreaView style={styles.safe}><StatusBar style="light"backgroundColor={colors.navy}/>{children}</SafeAreaView></SafeAreaProvider>}
function Button({label,onPress,disabled=false}:{label:string;onPress:()=>void;disabled?:boolean}){const heroAction=label==='VIEW LIVE OPERATIONS',inactive=disabled&&!heroAction;return<Pressable accessibilityRole="button"disabled={inactive}onPress={heroAction?()=>navigateAdmin('live'):onPress}style={({pressed})=>[styles.button,(pressed||inactive)&&{opacity:.45}]}><Text style={styles.buttonText}>{label}</Text></Pressable>}
function Card({children}:{children:React.ReactNode}){return<View style={styles.card}>{children}</View>}function Chip({text}:{text:string}){return<Text style={styles.chip}>{text}</Text>}function Center({text}:{text:string}){return<View style={styles.center}><ActivityIndicator color={colors.gold}/><Text style={styles.secondary}>{text}</Text></View>}function Empty({text}:{text:string}){return<View style={styles.empty}><Text style={styles.secondary}>{text}</Text></View>}
const styles=StyleSheet.create({
 safe:{flex:1,backgroundColor:colors.background},app:{flex:1,backgroundColor:colors.background},login:{flex:1,justifyContent:'center',padding:spacing.xl,gap:spacing.md,backgroundColor:colors.background},loginTitle:{fontSize:30,fontWeight:'900',color:colors.textPrimary,marginTop:spacing.xl},input:{minHeight:52,borderWidth:1,borderColor:colors.borderStrong,borderRadius:radii.sm,backgroundColor:colors.surfaceElevated,color:colors.textPrimary,paddingHorizontal:spacing.md},button:{minHeight:touchTarget,backgroundColor:colors.gold,borderRadius:radii.sm,alignItems:'center',justifyContent:'center'},buttonText:{fontWeight:'900',color:colors.background,letterSpacing:.7},
 error:{padding:spacing.md,backgroundColor:'rgba(228,75,75,.12)',borderWidth:1,borderColor:'rgba(228,75,75,.35)',color:colors.danger,borderRadius:radii.sm},success:{padding:spacing.md,backgroundColor:'rgba(76,175,106,.12)',borderWidth:1,borderColor:'rgba(76,175,106,.35)',color:colors.success,borderRadius:radii.sm},offline:{backgroundColor:colors.warning,textAlign:'center',fontWeight:'900',padding:spacing.sm,color:colors.background},top:{height:62,backgroundColor:colors.backgroundSecondary,paddingHorizontal:spacing.lg,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:colors.border},
 wordmark:{gap:2},brand:{fontSize:21,fontWeight:'900',letterSpacing:3,color:colors.textPrimary},brandTagline:{fontSize:8,fontWeight:'800',letterSpacing:1.2,color:colors.gold},logout:{color:colors.info,fontWeight:'900',fontSize:12},content:{padding:spacing.lg,gap:spacing.md,paddingBottom:90},hero:{minHeight:190,backgroundColor:colors.backgroundSecondary,borderRadius:radii.lg,padding:spacing.xl,overflow:'hidden',borderWidth:1,borderColor:colors.border},heroTitle:{fontSize:28,fontWeight:'900',color:colors.textPrimary,marginTop:spacing.xl},heroSubtitle:{color:colors.textSecondary,fontSize:15,marginTop:spacing.sm},heroMetrics:{flexDirection:'row',gap:spacing.xxl,marginTop:spacing.xl},miniValue:{fontSize:24,fontWeight:'900',color:colors.gold},miniLabel:{fontSize:10,fontWeight:'900',letterSpacing:1,color:colors.textSecondary},
 routeLine:{position:'absolute',width:180,height:4,borderRadius:2,backgroundColor:colors.gold,right:-30,bottom:25,transform:[{rotate:'-8deg'}]},section:{fontSize:19,fontWeight:'900',color:colors.textPrimary,marginTop:spacing.sm},metricGrid:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},metric:{width:'48%',backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radii.md,padding:spacing.lg},metricValue:{fontSize:27,fontWeight:'900',color:colors.textPrimary},note:{fontSize:12,color:colors.textMuted,lineHeight:18},secondary:{color:colors.textSecondary,lineHeight:20},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radii.md,padding:spacing.lg,gap:spacing.sm},cardTitle:{fontSize:17,fontWeight:'800',color:colors.textPrimary},chip:{alignSelf:'flex-start',paddingHorizontal:spacing.sm,paddingVertical:4,borderRadius:radii.pill,backgroundColor:'rgba(76,175,106,.12)',color:colors.success,fontSize:10,fontWeight:'900'},
 map:{height:300,borderRadius:radii.lg,overflow:'hidden',backgroundColor:colors.surfaceElevated},empty:{padding:spacing.xl,backgroundColor:colors.surfaceElevated,borderRadius:radii.md,alignItems:'center'},center:{flex:1,minHeight:130,alignItems:'center',justifyContent:'center',gap:spacing.sm},nav:{position:'absolute',bottom:0,left:0,right:0,height:70,flexDirection:'row',backgroundColor:colors.surface,borderTopWidth:1,borderTopColor:colors.border},navItem:{flex:1,alignItems:'center',justifyContent:'center',minHeight:touchTarget},navActive:{borderTopWidth:3,borderTopColor:colors.gold},navText:{fontSize:9,fontWeight:'900',color:colors.textMuted},navTextActive:{color:colors.gold},select:{padding:spacing.md,borderWidth:1,borderColor:colors.borderStrong,borderRadius:radii.sm,gap:4,backgroundColor:colors.surfaceElevated},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1,color:colors.textSecondary},modal:{flex:1,padding:spacing.lg,backgroundColor:colors.background,gap:spacing.md},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},choice:{padding:spacing.lg,borderBottomWidth:1,borderBottomColor:colors.border},heroImage:{borderRadius:radii.lg},heroShade:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(5,22,43,.55)'},heroCopy:{zIndex:1}
});
