import { ConflictException, ForbiddenException } from '@nestjs/common';
import { AccountStatus, Prisma, VerificationStatus } from '@prisma/client';
import { DriverComplianceService } from '../../common/driver-compliance.service';
import { TripsService } from './trips.service';

const driver=(id='driver-1',userId='user-1',overrides:Record<string,unknown>={})=>({id,userId,active:true,licenseNumber:'LICENSE-1',licenseExpiresAt:new Date(Date.now()+86_400_000),identityVerificationStatus:VerificationStatus.APPROVED,licenseVerificationStatus:VerificationStatus.APPROVED,user:{accountStatus:AccountStatus.ACTIVE},...overrides});
const trip=(id='trip-1',driverId='driver-1',vehicleId='vehicle-1')=>({id,driverId,vehicleId,status:'READY',vehicle:{active:true,assignedDriverId:driverId},route:{active:true}});
const uniqueConflict=()=>new Prisma.PrismaClientKnownRequestError('Unique constraint failed',{code:'P2002',clientVersion:'test'});

describe('TripsService trip state integrity',()=>{
 function setup(driverValue=driver()){
  const ready=trip();const tx:any={trip:{updateMany:jest.fn().mockResolvedValue({count:1}),findUniqueOrThrow:jest.fn().mockResolvedValue({...ready,status:'ACTIVE'})},tripEvent:{create:jest.fn()},auditLog:{create:jest.fn()},vehicleCurrentLocation:{deleteMany:jest.fn()}};
  const db:any={driver:{findUnique:jest.fn().mockResolvedValue(driverValue)},trip:{findUnique:jest.fn().mockResolvedValue(ready),findFirst:jest.fn().mockResolvedValue(null)},$transaction:jest.fn((operation:any)=>typeof operation==='function'?operation(tx):Promise.all(operation))};
  const live:any={publishStarted:jest.fn(),publishLocation:jest.fn(),publishEnded:jest.fn(),publishStop:jest.fn()};return{db,tx,live,service:new TripsService(db,live,new DriverComplianceService())};
 }
 it('allows a valid verified driver to start',async()=>{const{service,tx}=setup();await expect(service.start('user-1','trip-1')).resolves.toMatchObject({status:'ACTIVE'});expect(tx.trip.updateMany).toHaveBeenCalledWith(expect.objectContaining({where:{id:'trip-1',status:'READY'}}))});
 it('rejects direct start when compliance fails',async()=>{const{service,tx}=setup(driver('driver-1','user-1',{licenseExpiresAt:new Date(Date.now()-1)}));await expect(service.start('user-1','trip-1')).rejects.toBeInstanceOf(ForbiddenException);expect(tx.trip.updateMany).not.toHaveBeenCalled()});
 it('translates database uniqueness into a controlled conflict',async()=>{const{service,tx,live}=setup();tx.trip.updateMany.mockRejectedValue(uniqueConflict());await expect(service.start('user-1','trip-1')).rejects.toMatchObject({response:expect.objectContaining({code:'ACTIVE_TRIP_CONFLICT'})});expect(live.publishStarted).not.toHaveBeenCalled()});
 it.each([
  ['the same READY trip twice',trip('trip-1'),trip('trip-1')],
  ['different READY trips for one driver',trip('trip-1','driver-1','vehicle-1'),trip('trip-2','driver-1','vehicle-2')],
  ['different READY trips sharing one vehicle',trip('trip-1','driver-1','vehicle-1'),trip('trip-2','driver-2','vehicle-1')],
 ])('allows only one concurrent start for %s',async(_label,first,second)=>{
  const drivers:Record<string,any>={'user-1':driver('driver-1','user-1'),'user-2':driver('driver-2','user-2')};const trips:Record<string,any>={[first.id]:first,[second.id]:second};const activeDrivers=new Set<string>(),activeVehicles=new Set<string>(),activeTrips=new Set<string>();
  const tx:any={trip:{updateMany:jest.fn(async({where}:any)=>{const item=trips[where.id];if(activeTrips.has(item.id)||activeDrivers.has(item.driverId)||activeVehicles.has(item.vehicleId))throw uniqueConflict();activeTrips.add(item.id);activeDrivers.add(item.driverId);activeVehicles.add(item.vehicleId);return{count:1}}),findUniqueOrThrow:jest.fn(async({where}:any)=>({...trips[where.id],status:'ACTIVE'}))},tripEvent:{create:jest.fn()},auditLog:{create:jest.fn()}};
  const db:any={driver:{findUnique:jest.fn(({where}:any)=>Promise.resolve(drivers[where.userId]))},trip:{findUnique:jest.fn(({where}:any)=>Promise.resolve(trips[where.id])),findFirst:jest.fn().mockResolvedValue(null)},$transaction:jest.fn((cb:Function)=>cb(tx))};const live:any={publishStarted:jest.fn()};const service=new TripsService(db,live,new DriverComplianceService());const users=first.driverId===second.driverId?['user-1','user-1']:['user-1','user-2'];const results=await Promise.allSettled([service.start(users[0],first.id),service.start(users[1],second.id)]);
  expect(results.filter(result=>result.status==='fulfilled')).toHaveLength(1);const rejected=results.find(result=>result.status==='rejected')as PromiseRejectedResult;expect(rejected.reason).toBeInstanceOf(ConflictException);expect(rejected.reason.response.code).toBe('ACTIVE_TRIP_CONFLICT');expect(activeDrivers.size).toBe(1);expect(activeVehicles.size).toBe(1);expect(activeTrips.size).toBe(1);
 });
 it('allows only one concurrent completion and one event publication',async()=>{const{service,db,tx,live}=setup();db.trip.findUnique.mockResolvedValue({id:'trip-1',driverId:'driver-1',status:'ACTIVE'});let active=true;tx.trip.updateMany.mockImplementation(async()=>{if(!active)return{count:0};active=false;return{count:1}});tx.trip.findUniqueOrThrow.mockResolvedValue({id:'trip-1',status:'COMPLETED'});const results=await Promise.allSettled([service.complete('user-1','trip-1'),service.complete('user-1','trip-1')]);expect(results.filter(result=>result.status==='fulfilled')).toHaveLength(1);expect(live.publishEnded).toHaveBeenCalledTimes(1);expect(tx.tripEvent.create).toHaveBeenCalledTimes(1)});
 it('continues duplicate GPS ingestion after license expiry',async()=>{const{service,db}=setup(driver('driver-1','user-1',{licenseExpiresAt:new Date(Date.now()-1)}));db.trip.findUnique.mockResolvedValue({id:'trip-1',driverId:'driver-1',vehicleId:'vehicle-1',status:'ACTIVE',startedAt:new Date(Date.now()-60_000),lastPassedSequence:0,currentLocation:null,route:{stops:[]}});db.tripLocationHistory={findUnique:jest.fn().mockResolvedValue({suspicious:false,rejectionReason:null})};await expect(service.ingest('user-1','trip-1',{eventId:'existing',latitude:11,longitude:124,accuracy:10,recordedAt:new Date().toISOString()})).resolves.toMatchObject({accepted:true,duplicate:true,promoted:true})});
 it('blocks a new trip after license expiry',async()=>{const{service}=setup(driver('driver-1','user-1',{licenseExpiresAt:new Date(Date.now()-1)}));await expect(service.start('user-1','trip-1')).rejects.toMatchObject({response:expect.objectContaining({code:'LICENSE_EXPIRED'})})});
});

describe('TripsService trusted GPS promotion',()=>{
 function setup(currentLocation:any=null){const active={id:'trip-1',driverId:'driver-1',vehicleId:'vehicle-1',status:'ACTIVE',startedAt:new Date(Date.now()-300_000),lastPassedSequence:0,currentLocation,route:{stops:[]}};const history={findUnique:jest.fn().mockResolvedValue(null),create:jest.fn().mockResolvedValue({})};const current={upsert:jest.fn().mockResolvedValue({})};const tripModel={findUnique:jest.fn().mockResolvedValue(active),update:jest.fn().mockResolvedValue({})};const db:any={driver:{findUnique:jest.fn().mockResolvedValue(driver())},trip:tripModel,tripLocationHistory:history,vehicleCurrentLocation:current,$transaction:jest.fn((ops:any)=>Promise.all(ops))};const live:any={publishLocation:jest.fn(),publishStop:jest.fn()};return{service:new TripsService(db,live,new DriverComplianceService()),db,live,history,current}}
 const event=(overrides:any={})=>({eventId:'event-1',latitude:11,longitude:124,accuracy:10,recordedAt:new Date().toISOString(),...overrides});
 it('promotes and publishes a valid point',async()=>{const{service,current,live}=setup();await expect(service.ingest('user-1','trip-1',event())).resolves.toMatchObject({promoted:true,suspicious:false});expect(current.upsert).toHaveBeenCalled();expect(live.publishLocation).toHaveBeenCalledTimes(1)});
 it('quarantines an inaccurate point',async()=>{const{service,current,live,history}=setup();await expect(service.ingest('user-1','trip-1',event({accuracy:201}))).resolves.toMatchObject({promoted:false,rejectionReason:'ACCURACY_EXCEEDS_200_METERS'});expect(history.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({suspicious:true})}));expect(current.upsert).not.toHaveBeenCalled();expect(live.publishLocation).not.toHaveBeenCalled()});
 it('quarantines an impossible-speed point',async()=>{const{service,current,live}=setup({latitude:11,longitude:124,recordedAt:new Date(Date.now()-1000)});await expect(service.ingest('user-1','trip-1',event({latitude:12,speed:80}))).resolves.toMatchObject({promoted:false,rejectionReason:'IMPOSSIBLE_SPEED'});expect(current.upsert).not.toHaveBeenCalled();expect(live.publishLocation).not.toHaveBeenCalled()});
 it('resumes promotion for the next valid point',async()=>{const{service,current,live}=setup({latitude:11,longitude:124,recordedAt:new Date(Date.now()-60_000)});await service.ingest('user-1','trip-1',event({latitude:11.0001}));expect(current.upsert).toHaveBeenCalledTimes(1);expect(live.publishLocation).toHaveBeenCalledTimes(1)});
 it('keeps duplicate suspicious points idempotent',async()=>{const{service,db,current,live}=setup();db.tripLocationHistory.findUnique.mockResolvedValue({suspicious:true,rejectionReason:'IMPOSSIBLE_SPEED'});await expect(service.ingest('user-1','trip-1',event())).resolves.toMatchObject({duplicate:true,promoted:false});expect(db.tripLocationHistory.create).not.toHaveBeenCalled();expect(current.upsert).not.toHaveBeenCalled();expect(live.publishLocation).not.toHaveBeenCalled()});
});
