import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../common/prisma.service';
import { livePolicy } from '../../common/live-policy';
import { LiveGateway } from '../live/live.gateway';
import { DriverComplianceService } from '../../common/driver-compliance.service';
import { Prisma } from '@prisma/client';
type Event={eventId:string;latitude:number;longitude:number;accuracy:number;speed?:number;heading?:number;recordedAt:string};
const meters=(a:{latitude:number;longitude:number},b:{latitude:number;longitude:number})=>{const r=6371e3,p=(x:number)=>x*Math.PI/180,dlat=p(b.latitude-a.latitude),dlng=p(b.longitude-a.longitude),v=Math.sin(dlat/2)**2+Math.cos(p(a.latitude))*Math.cos(p(b.latitude))*Math.sin(dlng/2)**2;return 2*r*Math.asin(Math.sqrt(v));};
@Injectable()
export class TripsService {
 constructor(private db:PrismaService,private live:LiveGateway,private compliance:DriverComplianceService){}
 async driver(userId:string){const d=await this.db.driver.findUnique({where:{userId},include:{user:true}});if(!d)throw new ForbiddenException({statusCode:403,error:'Forbidden',code:'DRIVER_PROFILE_REQUIRED',message:'A driver profile is required.'});return d;}
 async assignment(userId:string){const d=await this.driver(userId);const trip=await this.db.trip.findFirst({where:{driverId:d.id,status:{in:['READY','ACTIVE']}},include:{driver:{select:{firstName:true,lastName:true}},vehicle:true,route:{include:{stops:{include:{stop:true},orderBy:{sequence:'asc'}}}}},orderBy:{scheduledDepartureAt:'asc'}});return trip?{...trip,compliance:this.compliance.evaluate(d)}:null;}
 async start(userId:string,id:string){const d=await this.driver(userId);this.compliance.assertCanStart(d);const trip=await this.db.trip.findUnique({where:{id},include:{vehicle:true,route:true}});if(!trip||trip.driverId!==d.id)throw new ForbiddenException({statusCode:403,error:'Forbidden',code:'TRIP_NOT_ASSIGNED',message:'Trip is not assigned to this driver.'});if(trip.status!=='READY')throw this.startConflict('TRIP_NOT_READY','Only a ready trip can start.');if(!trip.vehicle.active||trip.vehicle.assignedDriverId!==d.id)throw new ForbiddenException({statusCode:403,error:'Forbidden',code:'VEHICLE_NOT_AUTHORIZED',message:'This driver is not authorized to operate the assigned vehicle.'});if(!trip.route.active)throw new ForbiddenException({statusCode:403,error:'Forbidden',code:'ROUTE_NOT_AUTHORIZED',message:'This route is inactive or no longer authorized for this trip.'});const conflict=await this.db.trip.findFirst({where:{id:{not:id},status:'ACTIVE',OR:[{driverId:d.id},{vehicleId:trip.vehicleId}]}});if(conflict)throw this.startConflict();try{const active=await this.db.$transaction(async tx=>{const changed=await tx.trip.updateMany({where:{id,status:'READY'},data:{status:'ACTIVE',startedAt:new Date()}});if(changed.count!==1)throw this.startConflict('TRIP_NOT_READY','Only a ready trip can start.');const t=await tx.trip.findUniqueOrThrow({where:{id}});await tx.tripEvent.create({data:{tripId:id,type:'STARTED'}});await tx.auditLog.create({data:{actorId:userId,action:'trip.started',entityType:'Trip',entityId:id}});return t;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});this.live.publishStarted(id);return active;}catch(error){if(error instanceof ConflictException)throw error;if(error instanceof Prisma.PrismaClientKnownRequestError&&['P2002','P2034'].includes(error.code))throw this.startConflict();throw error;}}
 private startConflict(code='ACTIVE_TRIP_CONFLICT',message='Driver or vehicle is already on an active trip.'){return new ConflictException({statusCode:409,error:'Conflict',code,message});}
 async ingest(userId:string,tripId:string,e:Event){const d=await this.driver(userId);const trip=await this.db.trip.findUnique({where:{id:tripId},include:{currentLocation:true,route:{include:{stops:{include:{stop:true},orderBy:{sequence:'asc'}}}}}});if(!trip)throw new NotFoundException();if(trip.driverId!==d.id||trip.status!=='ACTIVE')throw new ForbiddenException('Trip ownership or state invalid');const at=new Date(e.recordedAt);if(at.getTime()>Date.now()+2*60_000||!trip.startedAt||at.getTime()<trip.startedAt.getTime()-60_000)throw new BadRequestException('Location timestamp is outside this active trip');const duplicate=await this.db.tripLocationHistory.findUnique({where:{eventId:e.eventId},select:{suspicious:true,rejectionReason:true}});if(duplicate)return{accepted:true,duplicate:true,suspicious:duplicate.suspicious,promoted:!duplicate.suspicious,rejectionReason:duplicate.rejectionReason};let rejectionReason:string|null=e.accuracy>200?'ACCURACY_EXCEEDS_200_METERS':null;if(trip.currentLocation){const seconds=(at.getTime()-trip.currentLocation.recordedAt.getTime())/1000;if(seconds<=0)throw new BadRequestException('Out-of-order location');if(!rejectionReason&&(meters(trip.currentLocation,e)/seconds>55||(e.speed??0)>55))rejectionReason='IMPOSSIBLE_SPEED';}const suspicious=Boolean(rejectionReason);
  if(suspicious){await this.db.tripLocationHistory.create({data:{...e,recordedAt:at,tripId,suspicious:true,rejectionReason}});return{accepted:true,duplicate:false,suspicious:true,promoted:false,rejectionReason};}
  await this.db.$transaction([this.db.tripLocationHistory.create({data:{...e,recordedAt:at,tripId,suspicious:false}}),this.db.vehicleCurrentLocation.upsert({where:{tripId},create:{...e,recordedAt:at,tripId,vehicleId:trip.vehicleId},update:{...e,recordedAt:at}}),this.db.trip.update({where:{id:tripId},data:{lastLocationAt:at}})]);
  await this.detectStops(trip,e);this.live.publishLocation(tripId,{tripId,vehicleId:trip.vehicleId,...e,recordedAt:at.toISOString()});return{accepted:true,duplicate:false,suspicious:false,promoted:true,rejectionReason:null};}
 async detectStops(trip:any,e:Event){const upcoming=trip.route.stops.filter((s:any)=>s.sequence>trip.lastPassedSequence);for(const rs of upcoming.slice(0,2)){const distance=meters(e,rs.stop),type=distance<=livePolicy.arrivedStopMeters?'STOP_ARRIVED':distance<=livePolicy.approachingStopMeters?'STOP_APPROACHING':null;if(!type)continue;await this.db.tripEvent.upsert({where:{tripId_type_stopId:{tripId:trip.id,type,stopId:rs.stopId}},create:{tripId:trip.id,type,stopId:rs.stopId,sequence:rs.sequence,metadata:{distanceMeters:Math.round(distance)}},update:{}});this.live.publishStop(trip.id,type,{stopId:rs.stopId,name:rs.stop.name,sequence:rs.sequence,distanceMeters:Math.round(distance)});if(type==='STOP_ARRIVED'&&rs.sequence>1)await this.db.trip.update({where:{id:trip.id},data:{lastPassedSequence:rs.sequence-1}});break;}}
 async ingestBatch(userId:string,tripId:string,events:Event[]){if(events.length>500)throw new BadRequestException('Maximum 500 events');const results=[];for(const e of [...events].sort((a,b)=>Date.parse(a.recordedAt)-Date.parse(b.recordedAt)))results.push(await this.ingest(userId,tripId,e));return{results};}
 async complete(userId:string,id:string){const d=await this.driver(userId),trip=await this.db.trip.findUnique({where:{id}});if(!trip||trip.driverId!==d.id)throw new ForbiddenException();const ended=await this.db.$transaction(async tx=>{const changed=await tx.trip.updateMany({where:{id,status:'ACTIVE'},data:{status:'COMPLETED',endedAt:new Date()}});if(changed.count!==1)throw new ConflictException({statusCode:409,error:'Conflict',code:'TRIP_NOT_ACTIVE',message:'Only an active trip can complete.'});await tx.vehicleCurrentLocation.deleteMany({where:{tripId:id}});await tx.tripEvent.create({data:{tripId:id,type:'COMPLETED'}});await tx.auditLog.create({data:{actorId:userId,action:'trip.completed',entityType:'Trip',entityId:id}});return tx.trip.findUniqueOrThrow({where:{id}});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});this.live.publishEnded(id);return ended;}
}
