import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../common/prisma.service';
import { livePolicy } from '../../common/live-policy';
import { LiveGateway } from '../live/live.gateway';
type Event={eventId:string;latitude:number;longitude:number;accuracy:number;speed?:number;heading?:number;recordedAt:string};
const meters=(a:{latitude:number;longitude:number},b:{latitude:number;longitude:number})=>{const r=6371e3,p=(x:number)=>x*Math.PI/180,dlat=p(b.latitude-a.latitude),dlng=p(b.longitude-a.longitude),v=Math.sin(dlat/2)**2+Math.cos(p(a.latitude))*Math.cos(p(b.latitude))*Math.sin(dlng/2)**2;return 2*r*Math.asin(Math.sqrt(v));};
@Injectable()
export class TripsService {
 constructor(private db:PrismaService,private live:LiveGateway){}
 async driver(userId:string){const d=await this.db.driver.findUnique({where:{userId},include:{user:true}});if(!d||!d.active||d.user.accountStatus!=='ACTIVE')throw new ForbiddenException('Active driver account required');return d;}
 async assignment(userId:string){const d=await this.driver(userId);return this.db.trip.findFirst({where:{driverId:d.id,status:{in:['READY','ACTIVE']}},include:{driver:{select:{firstName:true,lastName:true}},vehicle:true,route:{include:{stops:{include:{stop:true},orderBy:{sequence:'asc'}}}}},orderBy:{scheduledDepartureAt:'asc'}});}
 async start(userId:string,id:string){const d=await this.driver(userId);const trip=await this.db.trip.findUnique({where:{id},include:{vehicle:true,route:true}});if(!trip||trip.driverId!==d.id)throw new ForbiddenException('Trip is not assigned to this driver');if(trip.status!=='READY')throw new ConflictException('Only a ready trip can start');if(!trip.vehicle.active||trip.vehicle.assignedDriverId!==d.id||!trip.route.active)throw new BadRequestException('Assignment is no longer valid');const conflict=await this.db.trip.findFirst({where:{id:{not:id},status:'ACTIVE',OR:[{driverId:d.id},{vehicleId:trip.vehicleId}]}});if(conflict)throw new ConflictException('Driver or vehicle is already on an active trip');const active=await this.db.$transaction(async tx=>{const t=await tx.trip.update({where:{id},data:{status:'ACTIVE',startedAt:new Date()}});await tx.tripEvent.create({data:{tripId:id,type:'STARTED'}});await tx.auditLog.create({data:{actorId:userId,action:'trip.started',entityType:'Trip',entityId:id}});return t;});this.live.publishStarted(id);return active;}
 async ingest(userId:string,tripId:string,e:Event){const d=await this.driver(userId);const trip=await this.db.trip.findUnique({where:{id:tripId},include:{currentLocation:true,route:{include:{stops:{include:{stop:true},orderBy:{sequence:'asc'}}}}}});if(!trip)throw new NotFoundException();if(trip.driverId!==d.id||trip.status!=='ACTIVE')throw new ForbiddenException('Trip ownership or state invalid');const at=new Date(e.recordedAt);if(at.getTime()>Date.now()+2*60_000||!trip.startedAt||at.getTime()<trip.startedAt.getTime()-60_000)throw new BadRequestException('Location timestamp is outside this active trip');if(await this.db.tripLocationHistory.findUnique({where:{eventId:e.eventId}}))return{accepted:true,duplicate:true};let suspicious=e.accuracy>200;if(trip.currentLocation){const seconds=(at.getTime()-trip.currentLocation.recordedAt.getTime())/1000;if(seconds<=0)throw new BadRequestException('Out-of-order location');suspicious||=meters(trip.currentLocation,e)/seconds>55||(e.speed??0)>55;}
  await this.db.$transaction([this.db.tripLocationHistory.create({data:{...e,recordedAt:at,tripId,suspicious}}),this.db.vehicleCurrentLocation.upsert({where:{tripId},create:{...e,recordedAt:at,tripId,vehicleId:trip.vehicleId},update:{...e,recordedAt:at}}),this.db.trip.update({where:{id:tripId},data:{lastLocationAt:at}})]);
  if(!suspicious)await this.detectStops(trip,e);this.live.publishLocation(tripId,{tripId,vehicleId:trip.vehicleId,...e,recordedAt:at.toISOString(),suspicious});return{accepted:true,duplicate:false,suspicious};}
 async detectStops(trip:any,e:Event){const upcoming=trip.route.stops.filter((s:any)=>s.sequence>trip.lastPassedSequence);for(const rs of upcoming.slice(0,2)){const distance=meters(e,rs.stop),type=distance<=livePolicy.arrivedStopMeters?'STOP_ARRIVED':distance<=livePolicy.approachingStopMeters?'STOP_APPROACHING':null;if(!type)continue;await this.db.tripEvent.upsert({where:{tripId_type_stopId:{tripId:trip.id,type,stopId:rs.stopId}},create:{tripId:trip.id,type,stopId:rs.stopId,sequence:rs.sequence,metadata:{distanceMeters:Math.round(distance)}},update:{}});this.live.publishStop(trip.id,type,{stopId:rs.stopId,name:rs.stop.name,sequence:rs.sequence,distanceMeters:Math.round(distance)});if(type==='STOP_ARRIVED'&&rs.sequence>1)await this.db.trip.update({where:{id:trip.id},data:{lastPassedSequence:rs.sequence-1}});break;}}
 async ingestBatch(userId:string,tripId:string,events:Event[]){if(events.length>500)throw new BadRequestException('Maximum 500 events');const results=[];for(const e of [...events].sort((a,b)=>Date.parse(a.recordedAt)-Date.parse(b.recordedAt)))results.push(await this.ingest(userId,tripId,e));return{results};}
 async complete(userId:string,id:string){const d=await this.driver(userId),trip=await this.db.trip.findUnique({where:{id}});if(!trip||trip.driverId!==d.id)throw new ForbiddenException();if(trip.status!=='ACTIVE')throw new ConflictException('Only an active trip can complete');const ended=await this.db.$transaction(async tx=>{const t=await tx.trip.update({where:{id},data:{status:'COMPLETED',endedAt:new Date()}});await tx.vehicleCurrentLocation.deleteMany({where:{tripId:id}});await tx.tripEvent.create({data:{tripId:id,type:'COMPLETED'}});await tx.auditLog.create({data:{actorId:userId,action:'trip.completed',entityType:'Trip',entityId:id}});return t;});this.live.publishEnded(id);return ended;}
}
