import { ConflictException, ForbiddenException } from '@nestjs/common';
import { AccountStatus, Prisma, VerificationStatus } from '@prisma/client';
import { DriverComplianceService } from '../../common/driver-compliance.service';
import { TripsService } from './trips.service';

const driver=(id='driver-1',userId='user-1',overrides:Record<string,unknown>={})=>({id,userId,active:true,licenseNumber:'LICENSE-1',licenseExpiresAt:new Date(Date.now()+86_400_000),identityVerificationStatus:VerificationStatus.APPROVED,licenseVerificationStatus:VerificationStatus.APPROVED,user:{accountStatus:AccountStatus.ACTIVE},...overrides});
const trip=(id='trip-1',driverId='driver-1',vehicleId='vehicle-1')=>({id,driverId,vehicleId,status:'READY',scheduledDepartureAt:new Date(),vehicle:{active:true,assignedDriverId:driverId},route:{active:true}});
const uniqueConflict=()=>new Prisma.PrismaClientKnownRequestError('Unique constraint failed',{code:'P2002',clientVersion:'test'});
const serializationConflict=()=>new Prisma.PrismaClientKnownRequestError('Transaction failed',{code:'P2034',clientVersion:'test'});

describe('TripsService trip state integrity',()=>{
 function setup(driverValue=driver()){
  const ready=trip();const tx:any={trip:{updateMany:jest.fn().mockResolvedValue({count:1}),findUniqueOrThrow:jest.fn().mockResolvedValue({...ready,status:'ACTIVE'})},schedule:{updateMany:jest.fn()},tripEvent:{create:jest.fn()},auditLog:{create:jest.fn()},vehicleCurrentLocation:{deleteMany:jest.fn()}};
  const db:any={driverRouteAuthorization:{findUnique:jest.fn().mockResolvedValue({route:{active:true}})},driver:{findUnique:jest.fn().mockResolvedValue(driverValue)},trip:{findUnique:jest.fn().mockResolvedValue(ready),findFirst:jest.fn().mockResolvedValue(null)},$transaction:jest.fn((operation:any)=>typeof operation==='function'?operation(tx):Promise.all(operation))};
  const live:any={publishStarted:jest.fn(),publishLocation:jest.fn(),publishEnded:jest.fn(),publishStop:jest.fn()},lifecycle:any={reconcile:jest.fn(),reconcileTrip:jest.fn(),now:()=>new Date(),timing:(at:Date)=>({readyAt:new Date(at.getTime()-3600000),startDeadlineAt:new Date(at.getTime()+1800000)})};return{db,tx,live,service:new TripsService(db,live,new DriverComplianceService(),lifecycle)};
 }
 it('allows a valid verified driver to start',async()=>{const{service,tx}=setup();await expect(service.start('user-1','trip-1')).resolves.toMatchObject({status:'ACTIVE'});expect(tx.trip.updateMany).toHaveBeenCalledWith(expect.objectContaining({where:{id:'trip-1',status:'READY'}}))});
 it('rejects direct start when compliance fails',async()=>{const{service,tx}=setup(driver('driver-1','user-1',{licenseExpiresAt:new Date(Date.now()-1)}));await expect(service.start('user-1','trip-1')).rejects.toBeInstanceOf(ForbiddenException);expect(tx.trip.updateMany).not.toHaveBeenCalled()});
 it('translates database uniqueness into a controlled conflict',async()=>{const{service,tx,live}=setup();tx.trip.updateMany.mockRejectedValue(uniqueConflict());await expect(service.start('user-1','trip-1')).rejects.toMatchObject({response:expect.objectContaining({code:'ACTIVE_TRIP_CONFLICT'})});expect(live.publishStarted).not.toHaveBeenCalled()});
 it.each([
  ['the same READY trip twice',trip('trip-1'),trip('trip-1')],
  ['different READY trips for one driver',trip('trip-1','driver-1','vehicle-1'),trip('trip-2','driver-1','vehicle-2')],
  ['different READY trips sharing one vehicle',trip('trip-1','driver-1','vehicle-1'),trip('trip-2','driver-2','vehicle-1')],
 ])('allows only one concurrent start for %s',async(_label,first,second)=>{
  const drivers:Record<string,any>={'user-1':driver('driver-1','user-1'),'user-2':driver('driver-2','user-2')};const trips:Record<string,any>={[first.id]:first,[second.id]:second};const activeDrivers=new Set<string>(),activeVehicles=new Set<string>(),activeTrips=new Set<string>();
  const tx:any={trip:{updateMany:jest.fn(async({where}:any)=>{const item=trips[where.id];if(activeTrips.has(item.id)||activeDrivers.has(item.driverId)||activeVehicles.has(item.vehicleId))throw uniqueConflict();activeTrips.add(item.id);activeDrivers.add(item.driverId);activeVehicles.add(item.vehicleId);return{count:1}}),findUniqueOrThrow:jest.fn(async({where}:any)=>({...trips[where.id],status:'ACTIVE'}))},tripEvent:{create:jest.fn()},auditLog:{create:jest.fn()}};
  const db:any={driverRouteAuthorization:{findUnique:jest.fn().mockResolvedValue({route:{active:true}})},driver:{findUnique:jest.fn(({where}:any)=>Promise.resolve(drivers[where.userId]))},trip:{findUnique:jest.fn(({where}:any)=>Promise.resolve(trips[where.id])),findFirst:jest.fn().mockResolvedValue(null)},$transaction:jest.fn((cb:Function)=>cb(tx))};const live:any={publishStarted:jest.fn()},lifecycle:any={reconcileTrip:jest.fn(),now:()=>new Date(),timing:(at:Date)=>({readyAt:new Date(at.getTime()-3600000),startDeadlineAt:new Date(at.getTime()+1800000)})};const service=new TripsService(db,live,new DriverComplianceService(),lifecycle);const users=first.driverId===second.driverId?['user-1','user-1']:['user-1','user-2'];const results=await Promise.allSettled([service.start(users[0],first.id),service.start(users[1],second.id)]);
  expect(results.filter(result=>result.status==='fulfilled')).toHaveLength(1);const rejected=results.find(result=>result.status==='rejected')as PromiseRejectedResult;expect(rejected.reason).toBeInstanceOf(ConflictException);expect(rejected.reason.response.code).toBe('ACTIVE_TRIP_CONFLICT');expect(activeDrivers.size).toBe(1);expect(activeVehicles.size).toBe(1);expect(activeTrips.size).toBe(1);
 });
 it('allows only one concurrent completion and one event publication',async()=>{const{service,db,tx,live}=setup();db.trip.findUnique.mockResolvedValue({id:'trip-1',driverId:'driver-1',status:'ACTIVE'});let active=true;tx.trip.updateMany.mockImplementation(async()=>{if(!active)return{count:0};active=false;return{count:1}});tx.trip.findUniqueOrThrow.mockResolvedValue({id:'trip-1',status:'COMPLETED'});const results=await Promise.allSettled([service.complete('user-1','trip-1'),service.complete('user-1','trip-1')]);expect(results.filter(result=>result.status==='fulfilled')).toHaveLength(1);expect(live.publishEnded).toHaveBeenCalledTimes(1);expect(tx.tripEvent.create).toHaveBeenCalledTimes(1)});
 it('translates a completion serialization conflict without publishing',async()=>{const{service,db,live}=setup();db.trip.findUnique.mockResolvedValueOnce({id:'trip-1',driverId:'driver-1',status:'ACTIVE'}).mockResolvedValueOnce({status:'COMPLETED'});db.$transaction.mockRejectedValueOnce(serializationConflict());await expect(service.complete('user-1','trip-1')).rejects.toMatchObject({response:{statusCode:409,error:'Conflict',code:'TRIP_NOT_ACTIVE',message:'Only an active trip can complete.'}});expect(db.trip.findUnique).toHaveBeenLastCalledWith({where:{id:'trip-1'},select:{status:true}});expect(live.publishEnded).not.toHaveBeenCalled()});
 it('continues duplicate GPS ingestion after license expiry',async()=>{const{service,db}=setup(driver('driver-1','user-1',{licenseExpiresAt:new Date(Date.now()-1)}));db.trip.findUnique.mockResolvedValue({id:'trip-1',driverId:'driver-1',vehicleId:'vehicle-1',status:'ACTIVE',startedAt:new Date(Date.now()-60_000),lastPassedSequence:0,currentLocation:null,route:{stops:[]}});db.gpsIngestionEvent={deleteMany:jest.fn(),findUnique:jest.fn().mockResolvedValue({status:'PROMOTED',rejectionReason:null})};await expect(service.ingest('user-1','trip-1',{eventId:'existing',latitude:11,longitude:124,accuracy:10,recordedAt:new Date().toISOString()})).resolves.toMatchObject({accepted:true,duplicate:true,promoted:true})});
 it('blocks a new trip after license expiry',async()=>{const{service}=setup(driver('driver-1','user-1',{licenseExpiresAt:new Date(Date.now()-1)}));await expect(service.start('user-1','trip-1')).rejects.toMatchObject({response:expect.objectContaining({code:'LICENSE_EXPIRED'})})});
});

describe('TripsService trusted GPS promotion',()=>{
 function setup(currentLocation:any=null,promotions:number[]=[1]){const active={id:'trip-1',driverId:'driver-1',vehicleId:'vehicle-1',status:'ACTIVE',startedAt:new Date(Date.now()-300_000),lastPassedSequence:0,currentLocation,route:{stops:[]}};const ingestion={deleteMany:jest.fn(),findUnique:jest.fn().mockResolvedValue(null),create:jest.fn().mockResolvedValue({})};const tx:any={$queryRaw:jest.fn().mockImplementation(async()=>[active]),tripEvent:{upsert:jest.fn()},$executeRaw:jest.fn().mockImplementation(()=>Promise.resolve(promotions.shift()??1)),gpsIngestionEvent:ingestion,trip:{updateMany:jest.fn()}};const db:any={driverRouteAuthorization:{findUnique:jest.fn().mockResolvedValue({route:{active:true}})},driver:{findUnique:jest.fn().mockResolvedValue(driver())},trip:{findUnique:jest.fn().mockResolvedValue(active)},gpsIngestionEvent:ingestion,$transaction:jest.fn((cb:Function)=>cb(tx))};const live:any={publishLocation:jest.fn(),publishStop:jest.fn()},lifecycle:any={};return{service:new TripsService(db,live,new DriverComplianceService(),lifecycle),db,tx,live,ingestion}}
 const event=(overrides:any={})=>({eventId:'event-1',latitude:11,longitude:124,accuracy:10,recordedAt:new Date().toISOString(),...overrides});
 it('promotes a valid point into authoritative current state without raw coordinates in dedupe storage',async()=>{const{service,tx,live,ingestion}=setup();await expect(service.ingest('user-1','trip-1',event())).resolves.toMatchObject({promoted:true,suspicious:false});expect(tx.$executeRaw).toHaveBeenCalledTimes(1);expect(ingestion.create).toHaveBeenCalledWith({data:expect.objectContaining({eventId:'event-1',status:'PROMOTED',expiresAt:expect.any(Date)})});expect(ingestion.create.mock.calls[0][0].data).not.toHaveProperty('latitude');expect(live.publishLocation).toHaveBeenCalledTimes(1)});
 it('promotes consecutive valid points and leaves the latest authoritative',async()=>{const{service,tx,live}=setup(null,[1,1,1]);const base=Date.now();for(let i=0;i<3;i++)await service.ingest('user-1','trip-1',event({eventId:`event-${i}`,latitude:11+i/10000,recordedAt:new Date(base+i*5000).toISOString()}));expect(tx.$executeRaw).toHaveBeenCalledTimes(3);expect(live.publishLocation).toHaveBeenCalledTimes(3)});
 it('records inaccurate and impossible-speed dispositions without promoting or publishing',async()=>{const inaccurate=setup();await expect(inaccurate.service.ingest('user-1','trip-1',event({accuracy:201}))).resolves.toMatchObject({promoted:false,rejectionReason:'ACCURACY_EXCEEDS_200_METERS'});expect(inaccurate.ingestion.create).toHaveBeenCalledWith({data:expect.objectContaining({status:'REJECTED'})});expect(inaccurate.tx.$executeRaw).not.toHaveBeenCalled();expect(inaccurate.live.publishLocation).not.toHaveBeenCalled();const fast=setup({latitude:11,longitude:124,recordedAt:new Date(Date.now()-1000)});await expect(fast.service.ingest('user-1','trip-1',event({latitude:12,speed:80}))).resolves.toMatchObject({promoted:false,rejectionReason:'IMPOSSIBLE_SPEED'});expect(fast.tx.$executeRaw).not.toHaveBeenCalled()});
 it('keeps duplicate rejected points idempotent',async()=>{const{service,ingestion,tx,live}=setup();ingestion.findUnique.mockResolvedValue({status:'REJECTED',rejectionReason:'IMPOSSIBLE_SPEED'});await expect(service.ingest('user-1','trip-1',event())).resolves.toMatchObject({duplicate:true,promoted:false,suspicious:true});expect(ingestion.create).not.toHaveBeenCalled();expect(tx.$executeRaw).not.toHaveBeenCalled();expect(live.publishLocation).not.toHaveBeenCalled()});
 it('does not let an out-of-order point regress or publish current state',async()=>{const current={latitude:11,longitude:124,recordedAt:new Date()};const{service,ingestion,tx,live}=setup(current,[0]);await expect(service.ingest('user-1','trip-1',event({recordedAt:new Date(current.recordedAt.getTime()-5000).toISOString()}))).resolves.toMatchObject({promoted:false,rejectionReason:'STALE_LOCATION'});expect(ingestion.create).toHaveBeenCalledWith({data:expect.objectContaining({status:'STALE'})});expect(tx.trip.updateMany).not.toHaveBeenCalled();expect(live.publishLocation).not.toHaveBeenCalled()});
 it('sorts offline batches and safely deduplicates replayed events',async()=>{const{service,ingestion,tx,live}=setup(null,[1,1]);const base=Date.now();await expect(service.ingestBatch('user-1','trip-1',[event({eventId:'batch-2',recordedAt:new Date(base+5000).toISOString()}),event({eventId:'batch-1',recordedAt:new Date(base).toISOString()})])).resolves.toMatchObject({results:[{promoted:true},{promoted:true}]});expect(ingestion.create.mock.calls.map((call:any)=>call[0].data.eventId)).toEqual(['batch-1','batch-2']);expect(tx.$executeRaw).toHaveBeenCalledTimes(2);expect(live.publishLocation).toHaveBeenCalledTimes(2)});
 it('quarantines a pre-trip poison timestamp while promoting valid later batch events',async()=>{const{service,ingestion,tx,live,db}=setup(null,[1,1]);const startedAt=new Date(Date.now()-5*60_000);db.trip.findUnique.mockResolvedValue({id:'trip-1',driverId:'driver-1',vehicleId:'vehicle-1',status:'ACTIVE',startedAt,lastPassedSequence:0,currentLocation:null,route:{stops:[]}});const base=Date.now();const result=await service.ingestBatch('user-1','trip-1',[event({eventId:'poison-pretrip',recordedAt:new Date(startedAt.getTime()-61_000).toISOString()}),event({eventId:'valid-one',recordedAt:new Date(base).toISOString()}),event({eventId:'valid-two',recordedAt:new Date(base+5_000).toISOString()})]);expect(result.results).toMatchObject([{eventId:'poison-pretrip',disposition:'TERMINAL_INVALID',accepted:false,rejectionReason:'TIMESTAMP_BEFORE_ACTIVE_TRIP'},{eventId:'valid-one',disposition:'PROMOTED'},{eventId:'valid-two',disposition:'PROMOTED'}]);expect(ingestion.create.mock.calls.map((call:any)=>call[0].data.eventId)).toEqual(['poison-pretrip','valid-one','valid-two']);expect(tx.$executeRaw).toHaveBeenCalledTimes(2);expect(live.publishLocation).toHaveBeenCalledTimes(2)});
 it('quarantines a future poison timestamp without blocking valid neighbors',async()=>{const{service,ingestion,tx,live}=setup(null,[1,1]);const base=Date.now();const result=await service.ingestBatch('user-1','trip-1',[event({eventId:'valid-before',recordedAt:new Date(base).toISOString()}),event({eventId:'poison-future',recordedAt:new Date(base+2*60_000+1_000).toISOString()}),event({eventId:'valid-after',recordedAt:new Date(base+5_000).toISOString()})]);expect(result.results).toMatchObject([{eventId:'valid-before',disposition:'PROMOTED'},{eventId:'poison-future',disposition:'TERMINAL_INVALID',accepted:false,rejectionReason:'TIMESTAMP_TOO_FAR_IN_FUTURE'},{eventId:'valid-after',disposition:'PROMOTED'}]);expect(ingestion.create).toHaveBeenCalledWith({data:expect.objectContaining({eventId:'poison-future',status:'REJECTED',rejectionReason:'TIMESTAMP_TOO_FAR_IN_FUTURE'})});expect(tx.$executeRaw).toHaveBeenCalledTimes(2);expect(live.publishLocation).toHaveBeenCalledTimes(2)});
 it('returns duplicate disposition without reprocessing a replayed batch event',async()=>{const{service,ingestion,tx,live}=setup();ingestion.findUnique.mockResolvedValue({status:'PROMOTED',rejectionReason:null});await expect(service.ingestBatch('user-1','trip-1',[event({eventId:'replayed'})])).resolves.toMatchObject({results:[{eventId:'replayed',disposition:'DUPLICATE',duplicate:true,promoted:true}]});expect(ingestion.create).not.toHaveBeenCalled();expect(tx.$executeRaw).not.toHaveBeenCalled();expect(live.publishLocation).not.toHaveBeenCalled()});
 it('removes expired dedupe and quarantine metadata on bounded cleanup',async()=>{const{service,ingestion}=setup();await service.ingest('user-1','trip-1',event());expect(ingestion.deleteMany).toHaveBeenCalledWith({where:{expiresAt:{lte:expect.any(Date)}}})});
 it('rejects GPS if completion wins before the write lock',async()=>{
  const {service,tx,live}=setup();tx.$queryRaw.mockResolvedValue([{status:'COMPLETED',driverId:'driver-1',lastPassedSequence:0}]);
  await expect(service.ingest('user-1','trip-1',event())).rejects.toBeInstanceOf(ForbiddenException);
  expect(tx.$executeRaw).not.toHaveBeenCalled();expect(live.publishLocation).not.toHaveBeenCalled();
 });
 it('suppresses publication if completion wins after the GPS write commits',async()=>{
  const {service,tx,live}=setup();tx.$queryRaw.mockResolvedValueOnce([{status:'ACTIVE',driverId:'driver-1',lastPassedSequence:0}]).mockResolvedValueOnce([{status:'COMPLETED'}]);
  await service.ingest('user-1','trip-1',event());expect(tx.$executeRaw).toHaveBeenCalledTimes(1);expect(live.publishLocation).not.toHaveBeenCalled();
 });
 it('rechecks active state for every queued point',async()=>{
  const {service,tx,live}=setup();tx.$queryRaw.mockResolvedValueOnce([{status:'ACTIVE',driverId:'driver-1',lastPassedSequence:0}]).mockResolvedValueOnce([{status:'ACTIVE'}]).mockResolvedValue([{status:'COMPLETED'}]);
  await expect(service.ingestBatch('user-1','trip-1',[event(),event({eventId:'second'})])).rejects.toBeInstanceOf(ForbiddenException);
  expect(tx.$executeRaw).toHaveBeenCalledTimes(1);expect(live.publishLocation).toHaveBeenCalledTimes(1);
 });
 it('limits stop progression to the selected segment and persists it under the trip lock',async()=>{
  const {service,db,tx,live}=setup();const active=await db.trip.findUnique();active.events=[{metadata:{startStopId:'b',destinationStopId:'c'}}];
  active.route.stops=['a','b','c','d'].map((stopId,i)=>({stopId,sequence:i+1,stop:{name:stopId,latitude:11,longitude:124}}));
  await service.ingest('user-1','trip-1',event());
  expect(tx.tripEvent.upsert).toHaveBeenCalledWith(expect.objectContaining({create:expect.objectContaining({stopId:'b',sequence:2})}));
  expect(live.publishStop).toHaveBeenCalledWith('trip-1','STOP_ARRIVED',expect.objectContaining({stopId:'b'}));
 });

});
