import { clearSession, getAccessToken, getDeviceCredential, getRefreshToken, saveSession } from '../auth/session';
const configured=process.env.EXPO_PUBLIC_API_URL?.replace(/\/$/,'');
const appEnvironment=process.env.EXPO_PUBLIC_APP_ENV??(__DEV__?'development':'production');
if(!configured)throw new Error(`Missing EXPO_PUBLIC_API_URL for the ${appEnvironment} Driver Mobile build.`);
const parsed=new URL(configured);
if(appEnvironment!=='development'&&(parsed.protocol!=='https:'||['localhost','127.0.0.1','10.0.2.2'].includes(parsed.hostname)))throw new Error(`${appEnvironment} Driver Mobile builds require a non-local HTTPS API URL.`);
export const API_URL=configured;
export class ApiError extends Error{constructor(message:string,public status?:number){super(message)}}
async function raw(path:string,init:RequestInit={}){if(!API_URL)throw new ApiError('EXPO_PUBLIC_API_URL is not configured.');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const deviceCredential=await getDeviceCredential();return await fetch(`${API_URL}${path}`,{...init,signal:controller.signal,headers:{'content-type':'application/json',...(deviceCredential?{'x-sugat-device-credential':deviceCredential}:{}),...init.headers}})}catch(e){throw new ApiError(e instanceof Error&&e.name==='AbortError'?'Server request timed out.':'Cannot reach the SUGAT server.')}finally{clearTimeout(timer)}}
export async function login(email:string,password:string){const r=await raw('/auth/login',{method:'POST',body:JSON.stringify({email:email.trim().toLowerCase(),password,deviceCredential:await getDeviceCredential()??undefined})});if(!r.ok){const body=await r.json().catch(()=>({}));throw new ApiError(body.message??'Login failed.',r.status);}const session=await r.json();await saveSession(session);return session;}
let refreshInFlight:Promise<string>|null=null;
function refresh(){if(!refreshInFlight)refreshInFlight=renewSession().finally(()=>{refreshInFlight=null});return refreshInFlight}
async function renewSession(){const refreshToken=await getRefreshToken();if(!refreshToken)throw new ApiError('Session expired.',401);const r=await raw('/auth/refresh',{method:'POST',body:JSON.stringify({refreshToken,deviceCredential:await getDeviceCredential()??undefined})});if(!r.ok){await clearSession();throw new ApiError('Session expired. Please log in again.',401)}const session=await r.json();await saveSession(session);return session.accessToken as string;}
export async function authenticatedFetch(path:string,init:RequestInit={}){let token=await getAccessToken();if(!token)throw new ApiError('Session expired.',401);let r=await raw(path,{...init,headers:{...init.headers,authorization:`Bearer ${token}`}});if(r.status===401){token=await refresh();r=await raw(path,{...init,headers:{...init.headers,authorization:`Bearer ${token}`}})}return r;}
export async function logout(){const[token,refreshToken]=await Promise.all([getAccessToken(),getRefreshToken()]);try{if(token)await raw('/auth/logout',{method:'POST',headers:{authorization:`Bearer ${token}`},body:JSON.stringify({refreshToken,deviceCredential:await getDeviceCredential()??undefined})})}finally{await clearSession()}}
export async function changePassword(currentPassword:string,newPassword:string){const r=await authenticatedFetch('/auth/change-password',{method:'POST',body:JSON.stringify({currentPassword,newPassword})});if(!r.ok){let message='Password could not be changed.';try{const body=await r.json();message=Array.isArray(body.message)?body.message.join(', '):body.message??message}catch{}throw new ApiError(message,r.status)}const session=await r.json();await saveSession(session);return session}
export async function jsonRequest<T>(path:string,init:RequestInit={}){const r=await authenticatedFetch(path,init);if(!r.ok){let message=`Request failed (${r.status}).`;try{message=(await r.json()).message??message}catch{}throw new ApiError(Array.isArray(message)?message.join(', '):message,r.status)}return r.json() as Promise<T>;}
