import { clearSession, getAccessToken, getRefreshToken, saveSession } from '../auth/session';
const configured=process.env.EXPO_PUBLIC_API_URL?.replace(/\/$/,'');
export const API_URL=configured??'';
export class ApiError extends Error{constructor(message:string,public status?:number){super(message)}}
async function raw(path:string,init:RequestInit={}){if(!API_URL)throw new ApiError('EXPO_PUBLIC_API_URL is not configured.');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{return await fetch(`${API_URL}${path}`,{...init,signal:controller.signal,headers:{'content-type':'application/json',...init.headers}})}catch(e){throw new ApiError(e instanceof Error&&e.name==='AbortError'?'Server request timed out.':'Cannot reach the SUGAT server.')}finally{clearTimeout(timer)}}
export async function login(email:string,password:string){const r=await raw('/auth/login',{method:'POST',body:JSON.stringify({email:email.trim().toLowerCase(),password})});if(!r.ok)throw new ApiError(r.status===401?'Invalid email or password.':'Login failed.',r.status);const session=await r.json();await saveSession(session);return session;}
async function refresh(){const refreshToken=await getRefreshToken();if(!refreshToken)throw new ApiError('Session expired.',401);const r=await raw('/auth/refresh',{method:'POST',body:JSON.stringify({refreshToken})});if(!r.ok){await clearSession();throw new ApiError('Session expired. Please log in again.',401)}const session=await r.json();await saveSession(session);return session.accessToken as string;}
export async function authenticatedFetch(path:string,init:RequestInit={}){let token=await getAccessToken();if(!token)throw new ApiError('Session expired.',401);let r=await raw(path,{...init,headers:{...init.headers,authorization:`Bearer ${token}`}});if(r.status===401){token=await refresh();r=await raw(path,{...init,headers:{...init.headers,authorization:`Bearer ${token}`}})}return r;}
export async function jsonRequest<T>(path:string,init:RequestInit={}){const r=await authenticatedFetch(path,init);if(!r.ok){let message=`Request failed (${r.status}).`;try{message=(await r.json()).message??message}catch{}throw new ApiError(Array.isArray(message)?message.join(', '):message,r.status)}return r.json() as Promise<T>;}
