import NetInfo from '@react-native-community/netinfo';
import * as Linking from 'expo-linking';
import { StatusBar } from 'expo-status-bar';
import React,{useCallback,useEffect,useState}from'react';
import{ActivityIndicator,Alert,AppState,KeyboardAvoidingView,Platform,Pressable,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import{SafeAreaProvider,SafeAreaView}from'react-native-safe-area-context';
import{ApiError,API_URL,login}from'./src/api/client';
import{Assignment,completeTrip,getAssignment,startTrip}from'./src/api/trips';
import{clearSession,getAccessToken}from'./src/auth/session';
import{clearCompletedTripQueue,requestTrackingPermissions,restoreTracking,startTracking,stopTracking,syncQueue,trackingStatus}from'./src/location/tracker';
import{requestAndroidNotificationPermission}from'./src/location/android-permissions';

type GpsState={running:boolean;queued:number;lastUpload:string|null};
const ago=(iso:string|null)=>{if(!iso)return'NEVER';const s=Math.max(0,Math.round((Date.now()-Date.parse(iso))/1000));return s<60?`${s} SEC AGO`:`${Math.floor(s/60)} MIN AGO`};
export default function App(){const[booting,setBooting]=useState(true),[authenticated,setAuthenticated]=useState(false),[assignment,setAssignment]=useState<Assignment|null>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[online,setOnline]=useState(true),[gps,setGps]=useState<GpsState>({running:false,queued:0,lastUpload:null});
 const refreshGps=useCallback(async()=>{const s=await trackingStatus();setGps({running:s.running,queued:s.queued,lastUpload:s.lastUpload})},[]);
 const loadAssignment=useCallback(async()=>{try{const a=await getAssignment();setAssignment(a);if(a?.status==='ACTIVE'){await restoreTracking(a.id);try{await syncQueue(a.id)}catch{}}await refreshGps();return a}catch(e){if(e instanceof ApiError&&e.status===401){await clearSession();setAuthenticated(false);setError('Session expired. Please log in again.')}throw e}},[refreshGps]);
 useEffect(()=>{void(async()=>{try{if(await getAccessToken()){setAuthenticated(true);await loadAssignment()}}catch(e){if(e instanceof ApiError&&e.status===401){await clearSession();setAuthenticated(false)}else setError(e instanceof Error?e.message:'Unable to restore session.')}finally{setBooting(false)}})()},[loadAssignment]);
 useEffect(()=>NetInfo.addEventListener(s=>{const connected=Boolean(s.isConnected&&s.isInternetReachable!==false);setOnline(connected);if(connected&&assignment?.status==='ACTIVE')void syncQueue(assignment.id).then(refreshGps).catch(()=>{})}),[assignment?.id,assignment?.status,refreshGps]);
 useEffect(()=>{const timer=setInterval(()=>void refreshGps(),3000);const sub=AppState.addEventListener('change',state=>{if(state==='active'&&authenticated)void loadAssignment().catch(()=>{})});return()=>{clearInterval(timer);sub.remove()}},[authenticated,loadAssignment,refreshGps]);
 async function submitLogin(){if(!email.trim()||!password)return;setBusy(true);setError('');try{await login(email.trim(),password);setAuthenticated(true);await loadAssignment()}catch(e){setError(e instanceof Error?e.message:'Login failed.')}finally{setBusy(false)}}
 async function begin(){if(!assignment)return;setBusy(true);setError('');try{const notification=await requestAndroidNotificationPermission();if(!notification.granted){setError(notification.reason);return}const permission=await requestTrackingPermissions();if(!permission.granted){setError(permission.reason);return}await startTrip(assignment.id);await startTracking(assignment.id);await loadAssignment()}catch(e){setError(e instanceof Error?e.message:'Trip could not start.');try{await loadAssignment()}catch{}}finally{setBusy(false)}}
 function confirmComplete(){if(!assignment)return;Alert.alert('Complete this trip?','Passengers will stop seeing this vehicle after the backend confirms completion.',[{text:'Cancel',style:'cancel'},{text:'COMPLETE',style:'destructive',onPress:()=>void finish()}])}
 async function finish(){if(!assignment)return;setBusy(true);setError('');try{await syncQueue(assignment.id);await completeTrip(assignment.id);await stopTracking();await clearCompletedTripQueue(assignment.id);setAssignment(null);await loadAssignment()}catch(e){setError(`${e instanceof Error?e.message:'Completion failed.'} Tracking remains active until completion succeeds.`)}finally{setBusy(false)}}
 function logout(){if(assignment?.status==='ACTIVE'){setError('Complete the active trip before logging out so tracking is not orphaned.');return}Alert.alert('Log out?','SUGAT will not track your location while off duty.',[{text:'Cancel',style:'cancel'},{text:'LOG OUT',onPress:()=>void(async()=>{await stopTracking();await clearSession();setAuthenticated(false);setAssignment(null);setPassword('')})}])}
 if(booting)return<Shell><ActivityIndicator size="large"color="#175b40"/><Text style={styles.muted}>RESTORING SESSION…</Text></Shell>;
 if(!authenticated)return<Shell><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined}style={styles.center}><Text style={styles.brand}>SUGAT</Text><Text style={styles.tagline}>AYAW HULAT. SUGATA.</Text><Text style={styles.title}>Driver Login</Text><TextInput style={styles.input}autoCapitalize="none"autoCorrect={false}keyboardType="email-address"placeholder="Driver email"value={email}onChangeText={setEmail}/><TextInput style={styles.input}secureTextEntry placeholder="Password"value={password}onChangeText={setPassword}/>{error?<Text style={styles.error}>{error}</Text>:null}<Action label={busy?'SIGNING IN…':'SIGN IN'}disabled={busy||!email||!password}onPress={submitLogin}/><Text style={styles.server}>SERVER: {API_URL||'NOT CONFIGURED'}</Text></KeyboardAvoidingView></Shell>;
 const active=assignment?.status==='ACTIVE',next=assignment?.route.stops.find(s=>s.sequence>(assignment?.lastPassedSequence??0))?.stop.name;
 return<Shell><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><View><Text style={styles.brandSmall}>SUGAT DRIVER</Text><Text style={styles.tagline}>AYAW HULAT. SUGATA.</Text></View><Pressable onPress={logout}hitSlop={16}><Text style={styles.link}>LOG OUT</Text></Pressable></View>{assignment?<><View style={[styles.state,active&&styles.stateActive]}><Text style={styles.stateLabel}>{active?'● ACTIVE TRIP':'READY TO START'}</Text><Text style={styles.driver}>{assignment.driver.firstName} {assignment.driver.lastName}</Text></View><Card label="ASSIGNED VEHICLE"value={assignment.vehicle.displayName}detail={`${assignment.vehicle.type} · ${assignment.vehicle.bodyNumber??assignment.vehicle.plateNumber}`}/><Card label="ROUTE"value={assignment.route.name}detail={assignment.route.direction}/><Card label="DEPARTURE"value={new Date(assignment.scheduledDepartureAt).toLocaleString()}/>{active&&<><Card label="NEXT STOP"value={next??'Route destination'}/><View style={styles.grid}><Status label="GPS"value={gps.running?'ACTIVE':'NOT RUNNING'}good={gps.running}/><Status label="INTERNET"value={online?'ONLINE':'OFFLINE'}good={online}/></View><Card label="LOCATION SYNC"value={gps.queued?`${gps.queued} LOCATIONS WAITING`:'QUEUE CLEAR'}detail={`LAST UPLOAD: ${ago(gps.lastUpload)}`}/>{!online&&<Text style={styles.offline}>INTERNET OFFLINE{`\n`}GPS RECORDING CONTINUES{`\n`}WILL SYNC AUTOMATICALLY</Text>}</>}{error?<ErrorMessage text={error}/>:null}{error.includes('Settings')&&<Pressable onPress={()=>Linking.openSettings()}><Text style={styles.settings}>OPEN IPHONE SETTINGS</Text></Pressable>}<Action label={busy?'PLEASE WAIT…':active?'COMPLETE TRIP':'START TRIP'}danger={active}disabled={busy}onPress={active?confirmComplete:begin}/></>:<View style={styles.empty}><Text style={styles.emptyTitle}>WALAY ASSIGNED NGA BIYAHE KARON.</Text><Text style={styles.muted}>Contact SUGAT Admin if you expected an assignment.</Text>{error?<ErrorMessage text={error}/>:null}<Action label="REFRESH"disabled={busy}onPress={()=>void loadAssignment()}/></View>}</ScrollView></Shell>}
function Shell({children}:{children:React.ReactNode}){return<SafeAreaProvider><SafeAreaView style={styles.safe}><StatusBar style="dark"/><View style={styles.shell}>{children}</View></SafeAreaView></SafeAreaProvider>}
function Action({label,onPress,disabled,danger}:{label:string;onPress:()=>void;disabled?:boolean;danger?:boolean}){return<Pressable accessibilityRole="button"disabled={disabled}onPress={onPress}style={({pressed})=>[styles.action,danger&&styles.danger,(pressed||disabled)&&styles.dim]}><Text style={styles.actionText}>{label}</Text></Pressable>}
function Card({label,value,detail}:{label:string;value:string;detail?:string}){return<View style={styles.card}><Text style={styles.label}>{label}</Text><Text style={styles.cardValue}>{value}</Text>{detail?<Text style={styles.muted}>{detail}</Text>:null}</View>}
function Status({label,value,good}:{label:string;value:string;good:boolean}){return<View style={styles.card}><Text style={styles.label}>{label}</Text><Text style={[styles.status,!good&&styles.bad]}>{value}</Text></View>}
function ErrorMessage({text}:{text:string}){return<Text accessibilityRole="alert"style={styles.error}>{text}</Text>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#f3f0e7'},shell:{flex:1,padding:22},center:{flex:1,justifyContent:'center',gap:14},content:{gap:14,paddingBottom:30},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:18},brand:{fontSize:48,fontWeight:'900',letterSpacing:5,color:'#175b40'},brandSmall:{fontSize:20,fontWeight:'900',letterSpacing:2,color:'#175b40'},tagline:{fontSize:12,fontWeight:'800',letterSpacing:2,color:'#df563b'},title:{fontSize:26,fontWeight:'800',marginTop:24,color:'#163a2b'},input:{height:56,borderWidth:1,borderColor:'#c9cdc5',borderRadius:12,paddingHorizontal:16,backgroundColor:'#fff',fontSize:17},action:{minHeight:60,borderRadius:14,backgroundColor:'#176344',alignItems:'center',justifyContent:'center',marginTop:8},danger:{backgroundColor:'#a83f32'},dim:{opacity:.55},actionText:{color:'#fff',fontSize:16,fontWeight:'900',letterSpacing:1},server:{fontSize:10,color:'#78827d',textAlign:'center'},state:{padding:20,borderRadius:16,backgroundColor:'#e5e7df'},stateActive:{backgroundColor:'#d8eadb'},stateLabel:{fontWeight:'900',fontSize:13,color:'#176344',letterSpacing:1},driver:{fontSize:25,fontWeight:'800',color:'#183c2c',marginTop:7},card:{padding:18,borderRadius:14,backgroundColor:'#fff',gap:6,flex:1},label:{fontSize:10,fontWeight:'900',letterSpacing:1.5,color:'#708078'},cardValue:{fontSize:20,fontWeight:'800',color:'#183c2c'},muted:{color:'#6c7871',lineHeight:20},grid:{flexDirection:'row',gap:12},status:{fontWeight:'900',color:'#18754e'},bad:{color:'#b44837'},offline:{padding:16,borderRadius:12,backgroundColor:'#fff0cf',fontWeight:'800',lineHeight:22,color:'#704d0d',textAlign:'center'},error:{padding:14,borderRadius:10,backgroundColor:'#fde2dc',color:'#8d3024',lineHeight:20},settings:{color:'#175b40',fontWeight:'900',textAlign:'center',padding:12},empty:{flex:1,minHeight:500,justifyContent:'center',gap:18},emptyTitle:{fontSize:24,fontWeight:'900',color:'#183c2c',textAlign:'center'},link:{fontSize:12,fontWeight:'900',color:'#175b40'}});
