import { accessToken, clearSession, refreshToken, saveSession } from './session';
const API_URL = (process.env.EXPO_PUBLIC_API_URL ?? '').replace(/\/$/, '');
export const SOCKET_URL = API_URL.replace(/\/api\/v1$/, '');
export class ApiError extends Error { constructor(message: string, public status?: number) { super(message); } }
async function raw(path: string, init: RequestInit = {}) { if (!API_URL) throw new ApiError('EXPO_PUBLIC_API_URL is not configured.'); const controller = new AbortController(), timer = setTimeout(() => controller.abort(), 15_000); try { return await fetch(`${API_URL}${path}`, { ...init, signal: controller.signal, headers: { 'content-type': 'application/json', ...init.headers } }); } catch (error) { throw new ApiError(error instanceof Error && error.name === 'AbortError' ? 'Request timed out.' : 'Cannot reach SUGAT.'); } finally { clearTimeout(timer); } }
export async function login(email: string, password: string) { const response = await raw('/auth/login', { method: 'POST', body: JSON.stringify({ email: email.trim().toLowerCase(), password }) }); if (!response.ok) { let message = response.status === 401 ? 'Invalid email or password.' : 'Login failed.'; try { const body = await response.json(); message = Array.isArray(body.message) ? body.message.join(', ') : body.message ?? message; } catch {} throw new ApiError(message, response.status); } const session = await response.json(); await saveSession(session); return session; }
async function renew() { const token = await refreshToken(); if (!token) throw new ApiError('Session expired.', 401); const response = await raw('/auth/refresh', { method: 'POST', body: JSON.stringify({ refreshToken: token }) }); if (!response.ok) { await clearSession(); throw new ApiError('Session expired.', 401); } const session = await response.json(); await saveSession(session); return session.accessToken; }
export async function logout() { const [access, refresh] = await Promise.all([accessToken(), refreshToken()]); try { if (access) await raw('/auth/logout', { method: 'POST', headers: { authorization: `Bearer ${access}` }, body: JSON.stringify({ refreshToken: refresh }) }); } finally { await clearSession(); } }
export async function api<T>(path: string, init: RequestInit = {}) { let token = await accessToken(); if (!token) throw new ApiError('Session expired.', 401); let response = await raw(path, { ...init, headers: { ...init.headers, authorization: `Bearer ${token}` } }); if (response.status === 401) { token = await renew(); response = await raw(path, { ...init, headers: { ...init.headers, authorization: `Bearer ${token}` } }); } if (!response.ok) { let message = response.status === 403 ? 'Administrator authorization required.' : `Request failed (${response.status}).`; try { const body = await response.json(); message = Array.isArray(body.message) ? body.message.join(', ') : body.message ?? message; } catch {} throw new ApiError(message, response.status); } return response.json() as Promise<T>; }
