import { operatingTrip, startedSegmentEvents } from '../../common/trip-route-stops';
import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../common/prisma.service';
import { livePolicy, locationFreshness, type Freshness } from '../../common/live-policy';
import { EtaService } from './eta.service';
const km=(a:{latitude:number;longitude:number},b:{latitude:number;longitude:number})=>{const r=6371,p=(x:number)=>x*Math.PI/180,dlat=p(b.latitude-a.latitude),dlng=p(b.longitude-a.longitude),v=Math.sin(dlat/2)**2+Math.cos(p(a.latitude))*Math.cos(p(b.latitude))*Math.sin(dlng/2)**2;return 2*r*Math.asin(Math.sqrt(v));};
@Injectable()
export class LiveService {
 constructor(private db:PrismaService,private eta:EtaService){}
 stops(){return this.db.stop.findMany({where:{active:true},select:{id:true,name:true,description:true,cityMunicipality:true,province:true,latitude:true,longitude:true},orderBy:[{province:'asc'},{cityMunicipality:'asc'},{name:'asc'}]});}
 routes(){return this.db.route.findMany({where:{active:true},select:{id:true,name:true,direction:true,stops:{select:{sequence:true,boardingAllowed:true,dropoffAllowed:true,minutesFromPrevious:true,stop:{select:{id:true,name:true,latitude:true,longitude:true}}},orderBy:{sequence:'asc'}}}});}
 private etaContext(t:any,fromStopId:string,toStopId:string,freshness:Freshness){const from=t.route.stops.find((s:any)=>s.stopId===fromStopId),to=t.route.stops.find((s:any)=>s.stopId===toStopId);if(!from||!to||!from.stop.active||!to.stop.active||!from.boardingAllowed||!to.dropoffAllowed||from.sequence>=to.sequence)return null;return this.eta.context(t.route.stops,t.lastPassedSequence,t.currentLocation,freshness,from.sequence,to.sequence);}
 async search(fromStopId:string,toStopId:string){
  const trips=await this.db.trip.findMany({where:{status:'ACTIVE',route:{active:true,stops:{some:{stopId:fromStopId,boardingAllowed:true}}}},include:{events:startedSegmentEvents,vehicle:true,currentLocation:true,route:{include:{stops:{include:{stop:true},orderBy:{sequence:'asc'}}}}}});
  return trips.map(operatingTrip).flatMap(t=>{const from=t.route.stops.find(s=>s.stopId===fromStopId),to=t.route.stops.find(s=>s.stopId===toStopId);if(!from||!to||!from.stop.active||!to.stop.active||!from.boardingAllowed||!to.dropoffAllowed||from.sequence>=to.sequence||from.sequence<=t.lastPassedSequence||to.sequence<=t.lastPassedSequence)return[];const freshness=t.currentLocation?locationFreshness(t.currentLocation.recordedAt):'OFFLINE',etas=this.etaContext(t,fromStopId,toStopId,freshness);if(!etas||etas.boardingEta.status==='BOARDING_STOP_PASSED')return[];return[{tripId:t.id,vehicleId:t.vehicleId,occupancyStatus:t.occupancyStatus??null,occupancyUpdatedAt:t.occupancyUpdatedAt??null,freshnessPolicy:{liveAfterSeconds:livePolicy.liveAfterSeconds,offlineAfterSeconds:livePolicy.offlineAfterSeconds},location:t.currentLocation?{latitude:t.currentLocation.latitude,longitude:t.currentLocation.longitude,recordedAt:t.currentLocation.recordedAt,freshness}:null,vehicle:{type:t.vehicle.type,displayName:t.vehicle.displayName,bodyNumber:t.vehicle.bodyNumber},route:{name:t.route.name,direction:t.route.direction},status:t.status,boardingStop:from.stop,destinationStop:to.stop,nextStop:t.route.stops.find(s=>s.sequence>t.lastPassedSequence)?.stop??null,distanceKm:t.currentLocation?+km(t.currentLocation,from.stop).toFixed(1):null,boardingEta:etas.boardingEta,destinationEta:etas.destinationEta,remainingTripTime:etas.remainingTripTime,eta:etas.boardingEta,locationFreshness:freshness,freshness,lastUpdatedAt:t.currentLocation?.recordedAt??null,recordedAt:t.currentLocation?.recordedAt??null,scheduledDepartureAt:t.scheduledDepartureAt}];});
 }
 async getTrip(id:string,boardingStopId?:string,destinationStopId?:string){if(Boolean(boardingStopId)!==Boolean(destinationStopId))throw new BadRequestException('Boarding and destination stops must be provided together');const raw=await this.db.trip.findFirst({where:{id,status:'ACTIVE'},include:{events:startedSegmentEvents,vehicle:{select:{type:true,displayName:true,bodyNumber:true,plateNumber:true,conductionSticker:true}},route:{include:{stops:{include:{stop:true},orderBy:{sequence:'asc'}}}},currentLocation:true}});if(!raw)throw new NotFoundException('Active trip not found');const t=operatingTrip(raw);const freshness=t.currentLocation?locationFreshness(t.currentLocation.recordedAt):'OFFLINE';let etas=null;if(boardingStopId&&destinationStopId){etas=this.etaContext(t,boardingStopId,destinationStopId,freshness);if(!etas)throw new BadRequestException('Stops are not on this route');}return{id:t.id,vehicleId:t.vehicleId,occupancyStatus:t.occupancyStatus??null,occupancyUpdatedAt:t.occupancyUpdatedAt??null,status:t.status,scheduledDepartureAt:t.scheduledDepartureAt,vehicle:t.vehicle,route:{id:t.route.id,name:t.route.name,direction:t.route.direction,stops:t.route.stops},nextStop:t.route.stops.find(s=>s.sequence>t.lastPassedSequence)?.stop??null,trackingContext:boardingStopId&&destinationStopId?{boardingStopId,destinationStopId}:null,...(etas??{boardingEta:null,destinationEta:null,remainingTripTime:null}),freshnessPolicy:{liveAfterSeconds:livePolicy.liveAfterSeconds,offlineAfterSeconds:livePolicy.offlineAfterSeconds},location:t.currentLocation?{latitude:t.currentLocation.latitude,longitude:t.currentLocation.longitude,speed:t.currentLocation.speed,heading:t.currentLocation.heading,recordedAt:t.currentLocation.recordedAt,freshness}:null};}
 async getLocation(id:string){const l=await this.db.vehicleCurrentLocation.findUnique({where:{tripId:id},include:{trip:{select:{status:true}}}});if(!l||l.trip.status!=='ACTIVE')throw new NotFoundException('Live location unavailable');return{latitude:l.latitude,longitude:l.longitude,speed:l.speed,heading:l.heading,recordedAt:l.recordedAt,freshness:locationFreshness(l.recordedAt)};}
}
