import { BadRequestException } from '@nestjs/common';
import { VerificationStatus } from '@prisma/client';
import { VerificationService } from './verification.service';

describe('VerificationService',()=>{
 const upload=(byte=0xff,mimetype='image/jpeg')=>({buffer:Buffer.from([byte,0xd8,0xff,1]),mimetype,size:4});
 function setup(){const driver={id:'driver-1',userId:'user-1',licenseNumber:'L-1',licenseExpiresAt:new Date(Date.now()+86_400_000),identityVerificationStatus:VerificationStatus.UNVERIFIED,licenseVerificationStatus:VerificationStatus.UNVERIFIED};const submission={id:'submission-1',driverId:'driver-1',status:'PENDING_VERIFICATION',documents:[]};const tx:any={driverVerificationSubmission:{create:jest.fn().mockResolvedValue(submission),updateMany:jest.fn().mockResolvedValue({count:1}),findUniqueOrThrow:jest.fn().mockResolvedValue({...submission,status:'APPROVED'})},driver:{update:jest.fn()},auditLog:{create:jest.fn()}};const db:any={driver:{findUnique:jest.fn().mockResolvedValue(driver)},driverVerificationSubmission:{findFirst:jest.fn().mockResolvedValue(null),findMany:jest.fn(),findUnique:jest.fn().mockResolvedValue(submission)},driverVerificationDocument:{findUnique:jest.fn().mockResolvedValue({storageKey:'a'.repeat(48)+'.jpg',mimeType:'image/jpeg'})},$transaction:jest.fn((cb:Function)=>cb(tx))};const storage:any={store:jest.fn().mockResolvedValue({storageKey:'a'.repeat(48)+'.jpg',mimeType:'image/jpeg',sizeBytes:4,sha256:'hash'}),read:jest.fn().mockResolvedValue(Buffer.from('private')),remove:jest.fn()};return{service:new VerificationService(db,storage),db,tx,storage,driver}}
 it('requires license front, back, and selfie',async()=>{const{service}=setup();await expect(service.submit('user-1',{licenseFront:[upload()]}as any)).rejects.toBeInstanceOf(BadRequestException)});
 it('creates a pending submission without exposing storage keys',async()=>{const{service,tx}=setup();await service.submit('user-1',{licenseFront:[upload()],licenseBack:[upload()],selfie:[upload()]}as any);expect(tx.driverVerificationSubmission.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({status:'PENDING_VERIFICATION',documents:{create:expect.arrayContaining([expect.objectContaining({type:'LICENSE_FRONT'})])}})}));expect(tx.driver.update).toHaveBeenCalledWith(expect.objectContaining({data:{identityVerificationStatus:'PENDING_VERIFICATION',licenseVerificationStatus:'PENDING_VERIFICATION'}}))});
 it('requires a rejection reason and records review evidence',async()=>{const{service,tx}=setup();await expect(service.review('admin-1','submission-1','REJECTED')).rejects.toBeInstanceOf(BadRequestException);await service.review('admin-1','submission-1','REJECTED','Image is unreadable');expect(tx.driverVerificationSubmission.updateMany).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({rejectionReason:'Image is unreadable',reviewedById:'admin-1'})}));expect(tx.auditLog.create).toHaveBeenCalled()});
 it('retrieves private bytes only through the protected service path without returning a storage key',async()=>{const{service}=setup();await expect(service.document('document-1')).resolves.toEqual({data:Buffer.from('private'),mimeType:'image/jpeg'})});
});
