import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Location from 'expo-location';
import * as TaskManager from 'expo-task-manager';
import { Platform } from 'react-native';
import type { LocationEvent } from '@sugat/shared-types';
import { authenticatedFetch } from '../api/client';
import { trackingConfig } from './config';
import { reconcileTrackingLifecycle, type AuthoritativeAssignment } from './tracking-lifecycle';
import { acknowledgedEventIds, sanitizeNativeTelemetry } from './queue-policy';

const TASK='sugat-active-trip-location',QUEUE='sugat-location-queue',TRIP='sugat-active-trip',LAST_UPLOAD='sugat-last-location-upload';
let syncPromise:Promise<number>|null=null;
export type TrackingPermissionState='UNKNOWN'|'LOCATION_SERVICES_DISABLED'|'FOREGROUND_DENIED'|'BACKGROUND_DENIED'|'READY';
type BatchDisposition='PROMOTED'|'STALE'|'SUSPICIOUS'|'DUPLICATE'|'TERMINAL_INVALID'|'RETRYABLE';
type BatchResult={eventId:string;disposition:BatchDisposition};

async function readQueue():Promise<LocationEvent[]>{try{return JSON.parse((await AsyncStorage.getItem(QUEUE))??'[]')}catch{return[]}}
async function writeQueue(events:LocationEvent[]){await AsyncStorage.setItem(QUEUE,JSON.stringify(events.slice(-trackingConfig.maxQueueSize)))}
async function enqueue(event:LocationEvent){const prior=await readQueue();if(!prior.some(x=>x.eventId===event.eventId))await writeQueue([...prior,event]);}
const payload=(e:LocationEvent)=>({eventId:e.eventId,latitude:e.latitude,longitude:e.longitude,accuracy:e.accuracy,...sanitizeNativeTelemetry(e.speed,e.heading),recordedAt:e.recordedAt});

export async function syncQueue(tripId?:string){if(syncPromise)return syncPromise;syncPromise=(async()=>{const activeTrip=tripId??await AsyncStorage.getItem(TRIP);if(!activeTrip)return 0;let queue=await readQueue(),sent=0;while(true){const batch=queue.filter(e=>e.tripId===activeTrip).slice(0,trackingConfig.syncBatchSize);if(!batch.length)break;const r=await authenticatedFetch(`/driver/trips/${activeTrip}/locations/batch`,{method:'POST',body:JSON.stringify({events:batch.map(payload)})});if(!r.ok)throw new Error(`GPS synchronization failed (${r.status})`);let body:{results?:BatchResult[]};try{body=await r.json()}catch{break}const ids=acknowledgedEventIds(batch,body.results);if(!ids.size)break;queue=queue.filter(e=>e.tripId!==activeTrip||!ids.has(e.eventId));await writeQueue(queue);sent+=ids.size;if(body.results?.some(result=>ids.has(result.eventId)&&result.disposition==='PROMOTED'))await AsyncStorage.setItem(LAST_UPLOAD,new Date().toISOString())}return sent})().finally(()=>{syncPromise=null});return syncPromise;}

TaskManager.defineTask(TASK,async({data,error})=>{if(error||!data)return;const tripId=await AsyncStorage.getItem(TRIP);if(!tripId){try{if(await Location.hasStartedLocationUpdatesAsync(TASK))await stopTracking()}catch{}return}try{const response=await authenticatedFetch('/driver/assignment');if(response.ok){const assignment=await response.json()as AuthoritativeAssignment;await reconcileAuthoritativeTracking(assignment);if(assignment?.status!=='ACTIVE'||assignment.id!==tripId)return}else if(response.status===401||response.status===403){await reconcileAuthoritativeTracking(null);return}}catch(error){if((error as{status?:number})?.status===401){await reconcileAuthoritativeTracking(null);return}/* Network/server failure preserves intentional offline tracking for an ACTIVE local trip. */}for(const l of(data as{locations:Location.LocationObject[]}).locations){const telemetry=sanitizeNativeTelemetry(l.coords.speed,l.coords.heading);await enqueue({eventId:`${tripId}:${l.timestamp}:${l.coords.latitude.toFixed(6)}:${l.coords.longitude.toFixed(6)}`,tripId,latitude:l.coords.latitude,longitude:l.coords.longitude,accuracy:l.coords.accuracy??999,...telemetry,recordedAt:new Date(l.timestamp).toISOString()})}try{await syncQueue(tripId)}catch{/* The durable queue is retried by connectivity/app recovery. */}});

export async function trackingPermissionState():Promise<TrackingPermissionState>{try{if(!await Location.hasServicesEnabledAsync())return'LOCATION_SERVICES_DISABLED';const fg=await Location.getForegroundPermissionsAsync();if(fg.status!=='granted')return'FOREGROUND_DENIED';const bg=await Location.getBackgroundPermissionsAsync();if(bg.status!=='granted')return'BACKGROUND_DENIED';return'READY'}catch{return'UNKNOWN'}}
export function permissionRecoveryMessage(state:TrackingPermissionState){if(state==='LOCATION_SERVICES_DISABLED')return'Location Services are disabled. Enable Location in device Settings.';if(state==='FOREGROUND_DENIED')return'Precise location permission is required. Enable Location for SUGAT Driver in Settings.';if(state==='BACKGROUND_DENIED')return Platform.OS==='ios'?'Set Location to Always in iPhone Settings so tracking continues during an active trip.':'Set Location permission to Allow all the time in Android Settings so tracking continues with the screen locked.';if(state==='UNKNOWN')return'Location readiness could not be checked. Review Location permissions in Settings and try again.';return null}
export async function requestTrackingPermissions(){let state=await trackingPermissionState();if(state==='LOCATION_SERVICES_DISABLED')return{granted:false as const,state,reason:permissionRecoveryMessage(state)!};if(state==='FOREGROUND_DENIED'||state==='UNKNOWN'){const fg=await Location.requestForegroundPermissionsAsync();if(fg.status!=='granted'){state='FOREGROUND_DENIED';return{granted:false as const,state,reason:permissionRecoveryMessage(state)!}}}state=await trackingPermissionState();if(state==='BACKGROUND_DENIED'){const bg=await Location.requestBackgroundPermissionsAsync();if(bg.status!=='granted')return{granted:false as const,state,reason:permissionRecoveryMessage(state)!}}state=await trackingPermissionState();if(state!=='READY')return{granted:false as const,state,reason:permissionRecoveryMessage(state)!};return{granted:true as const,state};}
export async function startTracking(tripId:string){await AsyncStorage.setItem(TRIP,tripId);if(await Location.hasStartedLocationUpdatesAsync(TASK))return;await Location.startLocationUpdatesAsync(TASK,{accuracy:Location.Accuracy.High,timeInterval:trackingConfig.movingIntervalMs,distanceInterval:trackingConfig.distanceIntervalMeters,activityType:Location.ActivityType.AutomotiveNavigation,pausesUpdatesAutomatically:false,showsBackgroundLocationIndicator:true,foregroundService:{notificationTitle:'SUGAT trip tracking active',notificationBody:'Location is shared only for your active trip.'}});}
export async function restoreTracking(tripId:string){await AsyncStorage.setItem(TRIP,tripId);const permissionState=await trackingPermissionState();if(!await Location.hasStartedLocationUpdatesAsync(TASK)&&permissionState==='READY')await startTracking(tripId);return permissionState}
export async function stopTracking(){try{if(await Location.hasStartedLocationUpdatesAsync(TASK))await Location.stopLocationUpdatesAsync(TASK)}finally{await AsyncStorage.removeItem(TRIP)}}
export async function trackingStatus(){const[tripId,queue,lastUpload,running,permissionState]=await Promise.all([AsyncStorage.getItem(TRIP),readQueue(),AsyncStorage.getItem(LAST_UPLOAD),Location.hasStartedLocationUpdatesAsync(TASK),trackingPermissionState()]);return{tripId,queued:queue.filter(e=>!tripId||e.tripId===tripId).length,maxQueued:trackingConfig.maxQueueSize,lastUpload,running,permissionState}}
export async function clearCompletedTripQueue(tripId:string){const queue=await readQueue();await writeQueue(queue.filter(e=>e.tripId!==tripId))}
export function reconcileAuthoritativeTracking(assignment:AuthoritativeAssignment){return reconcileTrackingLifecycle(assignment,{localTripId:()=>AsyncStorage.getItem(TRIP),trackingRunning:()=>Location.hasStartedLocationUpdatesAsync(TASK),start:startTracking,stop:stopTracking,clearQueue:clearCompletedTripQueue})}
